### ISSUE TITLE
remove "RRA stars" and "RRb stars"; add "RRd stars"

### ISSUE THREAD

**Issue by rpoleski** [astrothesaurus/UAT#105]
The terms "RRA stars" and "RRb stars" are not used in literature for many years now. They were used in early RR Lyrae research, but it turn out that they are the same types of objects, and hence term RRab ("RRab stars" in UAT) is widely used. For supporting websites, see e.g.,

[GCVS](http://www.sai.msu.su/gcvs/gcvs/iii/vartype.txt)
[OGLE Atlas](http://www.astrouw.edu.pl/~soszynsk/atlas/RR_Lyr.html)

Also please consider adding "RRd stars", which are stars that show properties of RRab and RRc simultaneously.

**Comment by katieefrey** [comment]
RRa and RRb have been made non-preferred versions of RRab.

RRd added.

**Comment by katieefrey** [comment]
@rpoleski, from what I'm seeing, Bailey type stars is essentially synonymous with "RR Lyrae variable stars" or perhaps its a superset of RRab, RRc (and RRd?).  Is the concept "Bailey type stars" useful?

**Comment by rpoleski** [comment]
I don't think the term "Bailey type stars" is used nowadays. And yes, it is synonymous to "RR Lyrae variable stars", which are divided into RRab, RRc, and RRd subtypes.

**Comment by katieefrey** [comment]
Great, thanks that's what it looked like.  I'll make it a non-preferred version of RR Lyrae variables.
