### ISSUE TITLE
New Concept: Fast Radio Bursts

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#109]
https://twitter.com/ebpetroff/status/981124451759808513

Child of "Radio bursts" ?

**Comment by katieefrey** [comment]
alternate: "radio continuum: transients" -> "This might make more sense since "Fast" or Rapid are a relative(ly undefined) terms. Yet perhaps there is a goal of capturing the more colloquial terms too." - Gus Muench

**Comment by katieefrey** [comment]
What are "rapid bursts"?  Is there a relationship between "Fast radio bursts" and the existing UAT concept of "Rapid bursts"?  Perhaps they are synonymous?  The concept "Rapid bursts" doesn't seem well supported by the literature from what I am seeing, only 400 results in ADS, the majority of which seem to be about a specific low mass x-ray binary star named "The Rapid Burster."  My inclination is to update the preferred label to "Fast radio burst" (if they are synonymous) or have the concept "Rapid burster" reviewed for deprecation.

===
supporting articles:

https://ui.adsabs.harvard.edu/#abs/2015MNRAS.447..246P/abstract
"All FRBs discovered to date have been single radio events of millisecond duration."

https://ui.adsabs.harvard.edu/#abs/2007Sci...318..777L/abstract
"Transient radio sources are difficult to detect, but they can potentially provide insights into a wide variety of astrophysical phenomena. Of particular interest is the detection of short radio bursts, no more than a few milliseconds in duration, that may be produced by exotic events at cosmological distances, such as merging neutron stars or evaporating black holes. Pulsar surveys are currently among the few records of the sky with good sensitivity to radio bursts, and they have the necessary temporal and spectral resolution required to unambiguously discriminate between short-duration astrophysical bursts and terrestrial interference."

===

Following the pattern of existing transient source concepts, would "radio transient sources" make sense?  Is "Fast radio burst" preferable since it is more colloquially used?  Should it live as a child of "radio busts" or "transient sources" or both?  Is "radio bursts" a child of "transient sources" ?  Is there a difference between "burst astrophysics" and "transient sources"?

potential hierarchies (these are not exclusionary, the concept could live in both locations, and/or other locations if warranted):

1)
High energy astrophysics -> Transient sources -> X-ray transient sources
High energy astrophysics -> Transient sources -> Ultraviolet transient sources
High energy astrophysics -> Transient sources -> Gamma-ray transient sources
High energy astrophysics -> Transient sources -> Radio transient sources (?)

2)
High energy astrophysics -> Burst astrophysics -> Gamma-ray bursts
High energy astrophysics -> Burst astrophysics -> Optical bursts
High energy astrophysics -> Burst astrophysics -> Radio bursts
High energy astrophysics -> Burst astrophysics -> Radio bursts -> Fast radio bursts (?)
High energy astrophysics -> Burst astrophysics -> Rapid bursts [potentially synonymous with FRB?]
High energy astrophysics -> Burst astrophysics -> X-ray bursts

**Comment by augustfly** [comment]
Provenance on "radio continuum: transients" -- this keyword appears in the MNRAS keyword list from March 2017. [https://academic.oup.com/DocumentLibrary/mnras/keywords.pdf ; Accessed on 2018-08-09]

**Comment by katieefrey** [comment]
Accepted:

High energy astrophysics -> Transient sources -> Radio transient sources  [npt "fast radio bursts"]
