### ISSUE TITLE
Add Concept: Transients, submitted by Sarah Weissman (STScI) 8/8/2016 

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#11]
Added category for transients - X-ray source means something that is always there. A transient wouldn't be seen except for a brief period of time where it goes off and then you don't see it anymore. These were in APT but not in UAT.

High energy astrophysics -->Transients -->Gamma Ray bursters
High energy astrophysics -->Transients -->Gamma Ray transients
High energy astrophysics -->Transients -->UV transients
High energy astrophysics -->Transients -->X-ray transients
High energy astrophysics -->Transients

**Comment by katieefrey** [comment]
Does "Transients" have enough intrinsic context, or should the term be "Transient astronomical events"? 

Similar comments re: "X-ray transients" --> "X-ray transient events"?

**Comment by seweissman** [comment]
I think "transient source" might be the right thing to call it. E.g. http://imagine.gsfc.nasa.gov/science/objects/xray_transients1.html. 

Attempting to tag some astronomers to get opinions: @jrhastro, @scfleming, @rlwastro, @jegpeek.

**Comment by jrhastro** [comment]
Yes, I think "transient source" would be the preferred term.

**Comment by rlwastro** [comment]
Yep, I agree too -- "transient source" is correct.

On Dec 19, 2016, at 1:18 PM, Jonathan Hargis <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, I think "transient source" would be the preferred term.

**Comment by katieefrey** [comment]
These updates will be included in next release.

High energy astrophysics -->Transient sources -->Gamma Ray bursters
High energy astrophysics -->Transient sources -->Gamma Ray transient sources
High energy astrophysics -->Transient sources -->UV transient sources
High energy astrophysics -->Transient sources -->X-ray transient sources
High energy astrophysics -->Transient sources
