### ISSUE TITLE
Add Concepts to White Dwarfs, submitted by Sarah Weissman (STScI) 8/8/2016 

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#13]
Added more subtypes of White dwarf stars. See http://www.daviddarling.info/encyclopedia/W/whitedwarf.html.

... -->White dwarfs-->DA stars	
... -->White dwarfs-->DB stars	
... -->White dwarfs-->DC stars	
... -->White dwarfs-->DO stars-->BL Herculis stars
... -->White dwarfs-->DO stars-->PG 1159 stars
... -->White dwarfs-->DO stars	
... -->White dwarfs-->DZ stars	
... -->White dwarfs-->DQ stars

**Comment by katieefrey** [comment]
For the new sub types of White dwarf stars, the source document (http://www.daviddarling.info/encyclopedia/W/whitedwarf.html) indicates they should be written with lower case "d," but it looks like you use uppercase "D" in your original suggestion.  Which is preferred?

**Comment by seweissman** [comment]
I think the upper case is preferred. The lowercase "d" is historical usage. 

Although when talking about subdwarves as in "sdB" you do use the lowercase, so this is far from consistent.

**Comment by katieefrey** [comment]
Are "DQ Herculis stars" a subset of "DQ stars"?
