### ISSUE TITLE
Move concept: Emission line stars, submitted by Sarah Weissman (STScI) 8/8/2016 

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#16]
Moved "Emission line stars" out from "Variable stars" because not all emission line stars are variable.

**Comment by katieefrey** [comment]
I made this move, but should some concepts under "Emission line stars" should be poly-hierarchied back into "Variable stars"?

**Comment by seweissman** [comment]
I went through the list currently under Emission line stars that aren't already under variable stars.

I'm very sure that the following should be under variable stars:
- Luminous blue variables
- Me variable stars
- Z andromedae. They are a prototype for symbiotic stars but also variable: https://www.aavso.org/vsots_zand
- S Doradus stars. These should probably be under Luminous Blue Variables https://en.wikipedia.org/wiki/S_Doradus


I have questions about these:
**Herbig Ae/Be** - are sometimes variable?
"Sometimes Herbig Ae/Be stars show significant brightness variability. " https://en.wikipedia.org/wiki/Herbig_Ae/Be_star
Virtually all Herbig Ae/Be stars observed are irregular variables (called "UXors" after UX Ori), but there is a wide range of amplitudes from barely detectable to more than 4 mag in V.  (http://iopscience.iop.org/article/10.1086/300966/fulltext/)
So maybe UX Orionis aka UX Ori aka UXors are the subtype of Herbig Ae/Be that are variable and should be added as a term.

**Wolf-Rayet**
"Wolf–Rayet stars are massive hot stars that sometimes show variability," https://en.wikipedia.org/wiki/Variable_star
Should we add Wolf-rayet variable stars as a separate concept?

**Comment by seweissman** [comment]
Here are some resources on variable stars
https://www.aavso.org/types-variables
https://en.wikipedia.org/wiki/Variable_star
https://www.aavso.org/variables-what-are-they-why-observe-them

Also it might be worthwhile to look for anything else in the thesaurus that has "variable" in the name and isn't in the variable stars hierarchy. Can you do a query like this in Pool Party?

**Comment by katieefrey** [comment]
Switched this back to Arinelle milestone because the main suggestion (moving Emission Line stars out from under variable stars) was included in the v.2.0.0 release. The rest of these suggestions warrant further work, in a separate issue.
