### ISSUE TITLE
Modify concept: O giant stars, submitted by Sarah Weissman (STScI) 8/11/2016 

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#26]
And I just noticed that we used "O giant stars" instead of "O giants" like the rest of the "? giants" labels. These should probably be consistent.

**Comment by katieefrey** [comment]
Concept renamed "O giants."

**Comment by katieefrey** [comment]
The more I think on this, the more I see that this is part of a larger lack of consistency within the UAT.

There are many concepts where we tag "stars" on for clarity, such as "Variable stars" (vs Variables) and "Binary stars" (vs Binaries).  "B stars" is a concept, and simply using "B" would not make sense, so "B giant stars" seems like a more logical extension to me.

In the care of dwarf-objects, a word like "star" is crucial to differentiate between concepts such as "Dwarf galaxy", "Dwarf planet", and "dwarf novae".

Other terms that would need modifying include:
"Subdwarf" to "Subdwarf stars"
"Red giants" to "Red giant stars"
"G subgiants" to "G subgiant stars"
etc...

**Comment by seweissman** [comment]
I'm happy with this. Consistency = good.

**Comment by katieefrey** [comment]
I think I caught all of these.
