### ISSUE TITLE
Might be helpful to create a new-term issue template

### ISSUE THREAD

**Issue by pkgw** [astrothesaurus/UAT#264]
GitHub has a feature called [issue templates](https://help.github.com/articles/about-issue-and-pull-request-templates/) that let you create a template structure for new issues opened on a repository. It might be helpful to have such a template for new terms, to encourage uniformity and get people to spend a bit of time prepping their submission as opposed to just dashing off "add synchrotron n/t".

**Comment by katieefrey** [comment]
That is a really good idea, thank you!  I haven't fully explored the advnaced features of GitHub, didn't know this was possible.

**Comment by katieefrey** [comment]
Three templates added.  Please let me know if you have any feedback on them!

**Comment by pkgw** [comment]
These look great! I'm gonna say this issue can be closed.
