### ISSUE TITLE
Modify Concept: Magnetospheric radio emissions

### ISSUE THREAD

**Issue by BaptisteCecconi** [astrothesaurus/UAT#266]
The _Magnetospheric radio emissions_ (http://astrothesaurus.org/uat/998) concept is currently linked to 2 terms: 
- _Astronomical techniques_ (http://astrothesaurus.org/uat/1684)
- _Exoplanet detection methods_ (http://astrothesaurus.org/uat/489)

The rationale of these links are based on exoplanet search campaigns (not yet observed). However, _Magnetospheric radio emissions_ have been observed and studied for decades in the Solar System. This knowledge on Earth and planetary magnetospheric radio emissions provides the root idea of exoplanet _Magnetospheric radio emissions_ search campaigns. 

Two comments:
- _Magnetospheric radio emissions_  are a detection method for Exoplanet (although there is no observations of Exoplanet to date with this method)
- _Magnetospheric radio emissions_  are a phenomenon occurring in (exo-)planetary magnetospheres, and studied as such. 

So I recommend to move the concept  _Magnetospheric radio emissions_ under the _Planetary magnetosphere_ (http://astrothesaurus.org/uat/997) concept. 

The current links could be kept, I think, but we can discuss this here.

Cheers
Baptiste

**Comment by katieefrey** [comment]
changes will be in the next release.
