### ISSUE TITLE
New Concept: Technosignature

### ISSUE THREAD

**Issue by siemion** [astrothesaurus/UAT#269]
**Name the new concept**
Technosignature

**Describe the concept**
A signature (marker or indicator) of a technologically capable civilization. 

**Describe where the concept fits within the existing hierarchy**
In the existing hierarchy, would relate most directly to "astrobiology" -> "interdisciplinary astronomy"

Also would relate to "Search for Extraterrestrial Intelligence" (which is the subject of another issue)

**Provide 1-3 supporting articles**

arXiv:1901.04636
arXiv:1804.04571
arXiv:1701.06227

(There are many others)

**Please include any additional comments/feedback**

**Comment by katieefrey** [comment]
See also #290 for additional support.

Will be included in next release.

**Comment by katieefrey** [comment]
What about this hierarchy structure?

Interdisciplinary astronomy | Astrobiology | Biosignatures
Interdisciplinary astronomy | Astrobiology | Search for Extraterrestrial Intelligence | Technosignatures
Interdisciplinary astronomy | Astrobiology | Search for Extraterrestrial Intelligence
Interdisciplinary astronomy | Astrobiology | Xenobiology 
Interdisciplinary astronomy | Astrobiology

**Comment by katieefrey** [comment]
implemented as above (though PT of biosignatures is now "Biomarkers")
