### ISSUE TITLE
New Concept: Search for Extraterrestrial Intelligence

### ISSUE THREAD

**Issue by siemion** [astrothesaurus/UAT#270]
**Name the new concept**
Search for Extraterrestrial Intelligence (SETI)

**Describe the concept**
The Search for Extraterrestrial Intelligence or SETI is an area of research concerned with determining the prevalence of intelligent life in the universe.  Within astronomy, the principal activity of this research is searching for evidence of advanced technologies or "technosignatures."

**Describe where the concept fits within the existing hierarchy**
This concept relates most directly to "astrobiology" -> "interdisciplinary astronomy."
It also would be related to "technosignature" (which has been raised as an issue separately)

**Provide 1-3 supporting articles**
arXiv:1903.08381 

arXiv:1903.05839 

arXiv:1801.04868

**Please include any additional comments/feedback**

**Comment by katieefrey** [comment]
What about this hierarchy structure?

Interdisciplinary astronomy | Astrobiology | Biosignatures
Interdisciplinary astronomy | Astrobiology | Search for Extraterrestrial Intelligence | Technosignatures
Interdisciplinary astronomy | Astrobiology | Search for Extraterrestrial Intelligence
Interdisciplinary astronomy | Astrobiology | Xenobiology
Interdisciplinary astronomy | Astrobiology

**Comment by katieefrey** [comment]
accepted, will be in next release.
see also #269
