### ISSUE TITLE
Modify Concept: Meteor showers

### ISSUE THREAD

**Issue by mkelley** [astrothesaurus/UAT#273]
**Name the concept in question**
1034 : Meteor showers

**Describe the change**
"Meteor showers" is placed under "Interplanetary physics" but they are an atmospheric phenomenon.  A better location may be "Atmospheric science" or "Planetary atmospheres."

**Comment by katieefrey** [comment]
I agree that the current location is not good.  Would like more feedback/discussion on a new location.

**Comment by katieefrey** [comment]
Digging into this more.  It looks like we have concepts such as "Meteor trails" and "Fireballs" in the UAT as child concepts of "Meteors."  Similar to "Meteor shower" these two are related to atmospheric effects, and "meteor shower" would be a good sibling concept.

I think it is worth discussing in more detail if "shower" and these other concepts should be instead moved to something under "atmospheric science" but for now, "meteor shower" is being moved to "meteors."
