### ISSUE TITLE
Modify Concept: Meteorite composition

### ISSUE THREAD

**Issue by mkelley** [astrothesaurus/UAT#274]
**Name the concept in question**
1034 Meteorite composition

**Describe the change**
"Meteorite composition" is located under "Interplanetary physics."  Meteorites are exogenous materials on the surfaces of planets.  Instead, "Composition" may be added under "Solar system astronomy | Solar system | Meteoroids | Meteorites."

**Comment by stlibrary8** [comment]
STScI staff agree with Mike Kelley's suggestion:

Place Meterorites under:
Solar system astronomy | Solar system | Meteoroids | Meteorites

and further

Solar system astronomy | Solar system | Meteoroids | Meteorites | Meteorite composition

The study of the composition of meteorites is its own subfield and warrants its own narrower term.

**Comment by katieefrey** [comment]
Change implemented, will be in next release.
