### ISSUE TITLE
New Concept: Time domain astronomy

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#276]
**Name the new concept**
Time domain astronomy

**Describe the concept**
Studying how astronomical objects change over time.  Typically long term time domain astronomy is made possible with large sky surveys, historical photographic glass plates.

Related concepts could be:
- Time series analysis (from astrostats)
- High time resolution astrophysics (this is astronomy over really short time frames)

**Describe where the concept fits within the existing hierarchy**
child of "astronomical methods"

**Provide 1-3 supporting articles**
2018ExA....46..421S
2017JRASC.111..233P
DASCH: http://dasch.rc.fas.harvard.edu/project.php

**Please include any additional comments/feedback**
This has been suggested in the past by more than one astronomer, but never made it into an issue.

**Comment by mdlacy** [comment]
Maybe have additional  sub-categories of time domain astronomy:
-transients (things that appear and disappear)
-variables (things that change with time, but are always there)
-proper motions (things that move)

**Comment by katieefrey** [comment]
@mdlacy 

Transient sources, Variable stars, and Proper motion are all concepts that appear elsewhere.  Would it be acceptable to link these concepts to Time domain astornomy as "related terms"?

**Comment by mdlacy** [comment]
Yes, that sounds sensible to me.

**Comment by katieefrey** [comment]
accepted, implemented, will be seen in the next release.
