### ISSUE TITLE
Modify Concept: [Tidal tails(1701)]

### ISSUE THREAD

**Issue by robminchin** [astrothesaurus/UAT#277]
**Name the concept in question**
Which concept is this suggestion about? Please provide the numeric ID or URI for the concept as well.

Tidal tails(1701)

**Describe the change**
Should the concept be moved to another location within the hierarchy? Where and why?
Should the concept be renamed? Why?
Should this concept be merged with another concept? Which concept and why?

Rename to galactic tails. The name tidal tails presupposes a formation mechanism (tidal interactions), but tails can also come about through ram pressure stripping, and there are cases where the formation mechanism cannot be unambiguously determined.

**Please include any additional comments/feedback**

Alternatively, tidal tails and ram pressure stripped tails could both be sub-concepts of galactic tails, allowing for individual use if the mechanism is known and the generic use if either the mechanism cannot be determined or if both are being discussed.

**Comment by katieefrey** [comment]
Ram pressure stripped tails
- 2011ApJ...731...98T
- 2017ApJ...839..114J 
- 2013A&A...556A..99J 

Tidal tails
- 2014AAS...22324606R
- 2012MNRAS.420.2700K 
- 2012MNRAS.420.2700K

Galaxy tails
- 2015MNRAS.451.3192J "We investigate whether tidal interactions and/or ram pressure stripping are responsible for the formation of the H I tail..."

**Comment by katieefrey** [comment]
Leaning towards....

Galactic tails --> Tidal tails (1701)
Galactic tails --> Ram pressure stripped tails

**Comment by katieefrey** [comment]
Added concepts "Galaxy tails" and "Ram pressure stripped tails."

Galaxy structure -> Galaxy tails -> Tidal tails
Galaxy structure -> Galaxy tails -> Ram pressure stripped tails

I left Tidal tails as a child of "Interstellar medium."

Implemented, will be in the next release.
