### ISSUE TITLE
keywords don't form a hierarchy.

### ISSUE THREAD

**Issue by davidwhogg** [astrothesaurus/UAT#280]
Decision-making (#279) fits under Engineering (#278) but also under statistics and under bayesian statistics and other locations. Also, when I go down to classification I get support vector machine (but not target selection!) but svm can also be used for regression. So it isn't a hierarchy and that concept should be dropped. It is a network.

**Comment by katieefrey** [comment]
The UAT is best described as a polyhierarchy, where a concept can have multiple parents.  Mostly this means that there are many different ways to travel the hierarchical paths to find a concept.

The reason it is still a type of hierarchy is that a concept should not be it's own parent or grandparent, etc.  I think the polyhierarchy model works for the situation you described, where a concept could be found in multiple locations.

For an example in the current UAT see "Beta Cepheid variable stars" which is found under these five different parent concepts:
Cepheid variable stars
Early-type variable stars
Multi-periodic variable stars
Pulsating variable stars
Short period variable stars

**Comment by davidwhogg** [comment]
Okay good. Then I think I can live with this, although there are pathologies I can imagine.
