### ISSUE TITLE
Modify Concept: Beta Cepheid variable stars

### ISSUE THREAD

**Issue by rpoleski** [astrothesaurus/UAT#283]
**Name the concept in question**
"Beta Cepheid variable stars"
[http://astrothesaurus.org/uat/148](http://astrothesaurus.org/uat/148)

**Describe the change**
The concept should not be a child of "Cepheid variable stars." This is just a coincidence that prototypes of Delta Cep and Beta Cep stars are in the same constellation. See first paragraph of [https://en.wikipedia.org/wiki/Beta_Cephei_variable](https://en.wikipedia.org/wiki/Beta_Cephei_variable)

**Please include any additional comments/feedback**
See also frequently-reproduced Fig. 1 from [Eyer & Mowlavi 2008](https://ui.adsabs.harvard.edu/abs/2008JPhCS.118a2010E/abstract) (BCEP and CEP in green part).

**Comment by katieefrey** [comment]
Interesting, thanks, I did not realize this nuance before and I will look into it more.

From https://en.wikipedia.org/wiki/Cepheid_variable, other potential things to note and investigate:
- "Classical Cepheids (also known as Population I Cepheids, type I Cepheids, or Delta Cepheid variables)"
- "Type II Cepheids (also termed Population II Cepheids)... are divided into several subgroups by period. Stars with periods between 1 and 4 days are of the BL Her subclass, 10–20 days belong to the W Virginis subclass, and stars with periods greater than 20 days belong to the RV Tauri subclass."

also from that wiki entry, these two already exist as UAT concepts:
- Anomalous Cepheids
- Double-mode Cepheids

**Comment by rpoleski** [comment]
Yes, type II Cepheids are divided into 3 subclasses: BL Her, W Vir, and RV Tau. The period boundaries are 4-5 days and 20 days - see [this website](http://www.astrouw.edu.pl/~soszynsk/atlas/type_II_Cepheids.html), which was prepared by Igor Soszyński. There are references to his original papers there and on wikipedia page. He investigated this classification in detail.

**Comment by katieefrey** [comment]
We actually have concepts for all three of the subclasses, but not one for the type II cepheids, which is interesting... I want to look into that further.

**Comment by rpoleski** [comment]
I think adding "Type II Cepheids" with 3 child concepts is a good idea. The fact that BL Her, W Vir, and RV Tau are connected is well visible in the first plot on the webpage I've linked (it's period-luminosity relation, which is fundamental in astronomy). If you go [here](http://www.astrouw.edu.pl/~soszynsk/atlas/anomalous_Cepheids.html) you will see that Anomalous Cepheids are also a separate class.

**Comment by katieefrey** [comment]
accepted and implemented, will be in the next release.

Concept renamed to "Beta Cephei variable stars" (instead of cephei**d**).
No longer a child of "Cepheid variable stars."

"Type II Cepheid variable stars" added, and BL Her, W Vir, and RV Tau moved under it.
