### ISSUE TITLE
Modify Concept: (various solar regions)

### ISSUE THREAD

**Issue by danseaton** [astrothesaurus/UAT#285]
**Name the concept in question**
Solar K coronal region
http://astrothesaurus.org/uat/2042
Solar F coronal region
http://astrothesaurus.org/uat/1991
Solar E coronal region
http://astrothesaurus.org/uat/1990
Solar M coronal region
http://astrothesaurus.org/uat/984

**Describe the change**
The K, F, and E coronae are not regions, they are all different observational manifestations of the corona — they all refer to the same region, and the difference is the physical process by which generate the observations signatures we detect. These should be renamed as "Solar E corona", "Solar F corona", "Solar K corona".

I do not know what the M corona is supposed to be referring to. It is not in general use, and I recommend deprecating this keyword.

**Please include any additional comments/feedback**

**Comment by katieefrey** [comment]
K, F, and E corona will be updated as recommended above.

The M corona concept has its origins in the IAU thesuarus (http://www.mso.anu.edu.au/library/thesaurus/english/MREGIONS.html) and the IVOA Thesaurus (http://www.ivoa.net/rdf/Vocabularies/vocabularies-20091007/IVOAT/dict/M.html#mRegion).
Will need to look into this further.

**Comment by katieefrey** [comment]
"....the solar M-regions should be identified with the central portion of magnetically open solar regions, or coronal holes."
[1975P&SS...23..143G](https://ui.adsabs.harvard.edu/abs/1975P%26SS...23..143G/abstract)
Gulbrandsen, A. _The solar M-region problem - An old problem now facing its solution?_ Planetary and Space Science, Volume 23, Issue 1, p. 143-149.

It looks like "solar m regions" are something we now identify as "coronal holes".
@danseaton does this seem likely to you?

**Comment by danseaton** [comment]
Agreed, this sounds right to me. I would probably deprecate this keyword in favor of the much more widely used term coronal hole.

**Comment by katieefrey** [comment]
Suggestions accepted and implemented, will be included in the upcoming release.
