### ISSUE TITLE
New Concepts: Blazhko effect, DPV, BLAP, and OSARG

### ISSUE THREAD

**Issue by rpoleski** [astrothesaurus/UAT#286]
**Name the new concepts**
 - Blazhko effect
 - Double Periodic Variables
 - Blue Large-Amplitude Pulsator
 - OGLE Small Amplitude Red Giant

**Describe the concepts**
 - Blazhko effect -- this is phenomenon observed in RR Lyr type stars and demonstrates as changes of the light curve on timescales longer than pulsation period. The effect was first found more than 100 years ago and its origin is still not well understood and subject of active research.
 - Double Periodic Variables (DPV) -- some of the binary stars show additional period that this ~33 times longer than the orbital period and this group is called DPVs. Most of these systems are also showing eclipses, but that's not required. DPVs studied in detail show circumprimary discs. Note that the name seems general, but refers to only a specific group of binary stars.
 - Blue Large-Amplitude Pulsator (BLAP) -- a class of pulsating variable stars with short periods. These stars are hot (hence "blue" in name) and show relatively large amplitudes. The evolutionary state of these stars is not known.
 - OGLE Small Amplitude Red Giant (OSARG) -- red giant stars that pulsate with periods from 10 to 1000 days and in most cases variability is multi-periodic. OSARGs show multiple period-luminosity relations and most of the amplitudes are in mmag range. They are distinct from semi-regular variable stars.

**Describe where the concepts fit within the existing hierarchy**
New concepts fit under following concepts (some of these are in multiple locations in UAT):
 - Blazhko effect: "RRab variable stars", "RRc variable stars"
 - DPV: "Binary stars", "Eclipsing binary stars", "Multi-periodic variable stars"
 - BLAP: "Pulsating variable stars"
 - OSARG: "Long period variable stars", "Multi-periodic variable stars", "Red giant stars"

**Provide supporting articles**
 - Blazhko effect: 
[1907AN....175..325B](https://ui.adsabs.harvard.edu/abs/1907AN....175..325B/abstract), [1996A%26A...312..111J](https://ui.adsabs.harvard.edu/abs/1996A%26A...312..111J/abstract), [2003ApJ...598..597A](https://ui.adsabs.harvard.edu/abs/2003ApJ...598..597A/abstract), [2010MNRAS.409.1244S](https://ui.adsabs.harvard.edu/abs/2010MNRAS.409.1244S/abstract); see also [AAVSO article](https://www.aavso.org/unravelling-mystery-blazhko-effect-rr-lyrae-variables) and [wiki page](https://en.wikipedia.org/wiki/Blazhko_effect)
 - DPV: [2003A%26A...399L..47M](https://ui.adsabs.harvard.edu/abs/2003A%26A...399L..47M/abstract), [2005MNRAS.357.1219M](https://ui.adsabs.harvard.edu/abs/2005MNRAS.357.1219M/abstract), [2010AcA....60..179P](https://ui.adsabs.harvard.edu/abs/2010AcA....60..179P/abstract), [2013MNRAS.428.1594G](https://ui.adsabs.harvard.edu/abs/2013MNRAS.428.1594G/abstract)
 - BLAP: [2017NatAs...1E.166P](https://ui.adsabs.harvard.edu/abs/2017NatAs...1E.166P/abstract), [2018MNRAS.477L..30R](https://ui.adsabs.harvard.edu/abs/2018MNRAS.477L..30R/abstract), [2019ApJS..243...10P](https://ui.adsabs.harvard.edu/abs/2019ApJS..243...10P/abstract)
 - OSARG: [2004MNRAS.349.1059W](https://ui.adsabs.harvard.edu/abs/2004MNRAS.349.1059W/abstract) - introduced term OSARG, [2009AcA....59..239S](https://ui.adsabs.harvard.edu/abs/2009AcA....59..239S/abstract), [2013MNRAS.431.3189T](https://ui.adsabs.harvard.edu/abs/2013MNRAS.431.3189T/abstract), [2013A%26A...559A.137M](https://ui.adsabs.harvard.edu/abs/2013A%26A...559A.137M/abstract)

 
**Please include any additional comments/feedback**

None

**Comment by katieefrey** [comment]
These 4 concepts yield a relatively low number of results in ADS, however the results are pretty heavily skewed towards recent years, which indicates that they are newer classifications/areas of studies that could see a large amount of growth.  AAS Editor Steve Kawaler concurs.

All 4 are accepted, and the suggested locations seem good. [With the slight exception of placing Blazhko effect under RR Lyre stars... an effect is not a stellar type, but I'm not sure where else the concept could reasonably live. See also #289]

**Comment by katieefrey** [comment]
@rpoleski 
I'm working on adding these now, and... just to make sure, the new "Double Periodic Variables" are NOT the same thing as "Double-mode variable stars" (a concept that already exists in the UAT), right?

If that's the case can you help to provide a specific note about how these concepts differ?  I'm looking into it as well...

**Comment by rpoleski** [comment]
> These 4 concepts yield a relatively low number of results in ADS...

I don't agree with that statement for "Blazhko effect." The search for _abs:"blazhko"_ in ADS results 576 records. I did review a number of them and all are on RR Lyr, not on moon crater named Blazhko or on 2 Orders of Lenin that Sergey Blazhko received. 

> I'm working on adding these now, and... just to make sure, the new "Double Periodic Variables" are NOT the same thing as "Double-mode variable stars"

Correct.

**Comment by katieefrey** [comment]
> > These 4 concepts yield a relatively low number of results in ADS...
> 
> I don't agree with that statement for "Blazhko effect." The search for _abs:"blazhko"_ in ADS results 576 records. I did review a number of them and all are on RR Lyr, not on moon crater named Blazhko or on 2 Orders of Lenin that Sergey Blazhko received.

Ah, sorry about that.  I did an ADS search for these a few weeks ago, and just remembered the low numbers overall.  I only made mention of this at all because this is exactly what we want in the UAT; to be able to identify concepts that represent new and growing areas of study.
> 
> > I'm working on adding these now, and... just to make sure, the new "Double Periodic Variables" are NOT the same thing as "Double-mode variable stars"
> 
> Correct.

Great, thanks!

**Comment by katieefrey** [comment]
all concepts added, will be see in the next release.
