### ISSUE TITLE
Modify Concept: Carbon stars

### ISSUE THREAD

**Issue by SebastienDerriere** [astrothesaurus/UAT#302]
**Topic to modify**
[Carbon stars](http://astrothesaurus.org/uat/199)

**Describe the change**
The Simbad team noticed that the class "[Carbon stars](http://astrothesaurus.org/uat/199)" in the new IAU thesaurus is included in the "[chemically peculiar stars](http://astrothesaurus.org/uat/226)", and comprises any type of star with carbon-rich photosphere : AGB and RGB stars, as well as dwarf carbon stars and [carbon-enhanced metal poor (CEMP) stars](http://astrothesaurus.org/uat/2105). Historically, carbon stars were first identified as evolved red giants - AGB or RGB. For these the carbon enrichment of the photosphere is the result of the stellar evolution along the RGB and AGB branches. In the General Catalogue of Carbon Stars, less than 20 objects turned out to be dwarf carbon or CEMP stars out of 6900. In the Magellanic Clouds, out of about 15,000 spectroscopically identified carbon stars, only a few are galactic dwarf carbon stars.

In Simbad we thus distinguish between carbon stars and dwarf carbon / CEMP stars. The object type "Carbon star" in Simbad is used only for evolved stars, mostly AGB and RGB stars. Dwarf carbon and CEMP stars are classified as Chemically peculiar stars; the rest of the information is contained in the spectral type : like dC or like CEMP. We think that to mix any type of carbon-rich stars is a loss of information, because then "carbon stars" does not refer to an evolutionary stage anymore, but just to chemical composition of the photosphere. We by the way noticed that [S stars](http://astrothesaurus.org/uat/1421) are under evolved stars in the thesaurus.

Two examples :

V*Y Pav   Type = C*     SpT = C7,3

G 77-61   Type = Pe*   SpT = dC-J_CH5

**Please include any additional comments/feedback**
Suggested by Cécile Loup, in charge of scientific contents of SIMBAD at Observatoire astronomique de Strasbourg.

**Comment by katieefrey** [comment]
From Steve Kawaler: Carbon Stars - I agree with maintaining a distinction between evolved (giant) stars and the CEMP stars

**Comment by katieefrey** [comment]
@SebastienDerriere 

Can you tell me more directly what change is being proposed here?

I'm not sure what you (or Cécile Loup) want changed in the UAT.  It sounds mostly like you think there should be one concept for Carbon Stars, and another concept for CEMP stars, but the UAT already has that distinction (Carbon Stars http://astrothesaurus.org/uat/199  and 
CEMP Stars http://astrothesaurus.org/uat/2105)

Also, can you clarify the comment about "S Stars" in that github issue as well?

**Comment by katieefrey** [comment]
Perhaps the suggestion is to put "Carbon stars" under "Evolved stars"?

**Comment by katieefrey** [comment]
unable to get more feedback on this suggestion, closing it for now.
