### ISSUE TITLE
New Concept: Planetary surfaces

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#303]
**Planetary surfaces** Propose to add broader term "Planetary surfaces" and "Exoplanet surfaces" as child term to "Planetary structure" and "Exoplanet structure".

Currently there does not appear to be a concept to describe "Planetary Surfaces" under "Planetary structure" as a broad concept on same level as "Planetary cores", for example. Researchers propose to use Hubble to study the surface characteristics of planets and other bodies in the Solar System and requested to add this to the Astronomer's Proposal Toolkit science keywords. It was then found that there appears to be no equivalent concept in the current version of the UAT. More specific child terms to "Planetary surfaces" are being proposed in a ticket to follow.

Also, under Exoplanet Astronomy there are more specific terms than "Exoplanet surfaces", such as Exoplanet surface characteristics
    Exoplanet surface composition
    Exoplanet surface variability
 Will be proposing related Exoplanet equivalent, "Exoplanet surfaces", in ticket to follow.

Proposed hierarchy:
Solar system astronomy... Planetary science... Planetary structure... Planetary surfaces

Related articles and conf proceedings for Solar System planetary surfaces:
https://ui.adsabs.harvard.edu/abs/2019EPSC...13.1683F/abstract
https://ui.adsabs.harvard.edu/abs/2018JGRE..123.2564P/abstract
https://ui.adsabs.harvard.edu/abs/2018M%26PS...53..554W/abstract
https://ui.adsabs.harvard.edu/abs/2018P%26SS..150..141M/abstract

Related to Exoplanet ticket to be submitted: https://ui.adsabs.harvard.edu/abs/2019AJ....158..246B/abstract; https://ui.adsabs.harvard.edu/abs/2019AsBio..19..867H/abstract

**Comment by katieefrey** [comment]
Planetary science --> Planetary structure --> Planetary surfaces 

accepted and implemented, this will be seen in the next release.

see also #304
