### ISSUE TITLE
New Concepts (child terms to newly proposed "Planetary surfaces"): Surface processes, Surface composition, Surface variability

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#304]
Propose three child terms to newly proposed "Planetary surfaces":
Surface processes
Surface composition
Surface variability

Indifferent if labeled with or without "Planetary", but in literature it is clear much more natural to simply say:
Surface processes
Surface composition
Surface variability

as opposed to
Planetary surface processes
Planetary surface composition
Planetary surface variability 

The "Planetary surface processes" etc. can be synonyms to more natural "Surface processes".

Unsure if added layer to align with Exoplanet hierarchy is really needed, i. e.,:
Planetary structure (already in UAT)
...Planetary surfaces (proposed in ticket # 303) 
.......Surface processes (proposed in this ticket)
**[......Surface characteristics] -- unsure if really needed; only purpose is to align with Exoplanet equivalent. It feels forced based on literature search. I think it is enough to say "Planetary surfaces" (PT), then "Surface processes", "Surface composition", "Surface variability" without added layer, but not adverse to added composition and variability under another layer of hierarchy if curator thinks this approach is warranted.**
.........Surface composition (proposed in this ticket)
.........Surface variability (proposed in this ticket)

Relevant articles:
https://ui.adsabs.harvard.edu/abs/2019Icar..333..496L/abstract
https://ui.adsabs.harvard.edu/abs/2019Icar..321..508W/abstract
https://ui.adsabs.harvard.edu/abs/2018A%26A...609A.113C/abstract
https://ui.adsabs.harvard.edu/abs/2017Icar..287..218P/abstract

https://ui.adsabs.harvard.edu/abs/2019LPICo2089.6254S/abstract
https://ui.adsabs.harvard.edu/abs/2017Icar..282..214B/abstract
https://ui.adsabs.harvard.edu/abs/2008JGRE..11312S32H/abstract

https://ui.adsabs.harvard.edu/abs/2017ApJ...837L..27Z/abstract (relates to Exoplanets)
https://ui.adsabs.harvard.edu/abs/2015AGUFM.P13B2122S/abstract

These child terms were proposed by two Solar System/planetary researchers at STScI.

**Comment by katieefrey** [comment]
This is what I'm looking at now...
Planetary science --> Planetary structure --> Planetary surfaces --> Surface variability
Planetary science --> Planetary structure --> Planetary surfaces --> Surface composition
Planetary science --> Planetary structure --> Planetary surfaces --> Surface processes
Planetary science --> Planetary structure --> Planetary surfaces --> Surface ices

The concept in general are fine and will be added, but I'm not sure about leaving off the "Planetary," it mostly depends on how similar concepts are (or how soon they could be) relevant to exoplanet study.  I want to look into this and try to get some additional input.

**Comment by katieefrey** [comment]
Actually, I see that we currently have "atmospheric variability" and then "exoplanet atmospheric variability"  so I will just stick with that established convention.

Accepted, implemented, will be in the next version!

**Comment by katieefrey** [comment]
edited my comment above, because I had mistyped. I had meant we already had at least one concept that was an "atmospheric" specific concept prior to these suggestions.  Anyways, I'm going with it for now.
