### ISSUE TITLE
New Concept: Exoplanet surfaces

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#305]
Propose adding:
"Exoplanet surfaces" as child term to "Exoplanet structure"

Propose adding more general layer between "Exoplanet structure" and "Exoplanet surface characteristics" as follows:
Exoplanet astronomy
...Exoplanet structure
......Exoplanet surfaces (proposed new term)
.........Exoplanet surface characteristics

Supporting articles
https://ui.adsabs.harvard.edu/abs/2019AJ....158..246B/abstract
https://ui.adsabs.harvard.edu/abs/2019AsBio..19..867H/abstract
https://ui.adsabs.harvard.edu/abs/2018A%26A...612L...3M/abstract
https://ui.adsabs.harvard.edu/abs/2015AGUFM.P33B2130W/abstract
https://ui.adsabs.harvard.edu/abs/2018arXiv180405094H/abstract
https://ui.adsabs.harvard.edu/abs/2014LPI....45.1052C/abstract

Did not propose "Exoplanet surface processes" as new child term to proposed "Exoplanet surfaces" to align with Solar System equivalent since there is not much in the literature at this time specifically on "surface processes" of exoplanets.

**Comment by katieefrey** [comment]
accepted Exoplanet surfaces and the suggested hierarchy.  implemented, will be in the next release.
