### ISSUE TITLE
New Concepts: "Atmospheric composition" and "Atmospheric variability" (child terms to "Planetary atmospheres")

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#306]
Propose two new child terms to "Planetary atmospheres" at request of STScI planetary/Solar System researchers. There are equivalent terms in the UAT under "Exoplanet atmospheres". Propose concepts at same level for Solar System astronomy:

Solar system astronomy
...Planetary science
......Planetary atmospheres
.........Atmospheric composition (proposed new term)
.........Atmospheric variability (proposed new term)

Supporting literature:
https://ui.adsabs.harvard.edu/abs/2019EPSC...13..452A/abstract
https://ui.adsabs.harvard.edu/abs/2018Icar..311...23L/abstract
https://ui.adsabs.harvard.edu/abs/2017LPICo2022.8018H/abstract
https://ui.adsabs.harvard.edu/abs/2018AGUFM.P32A..08W/abstract

**Comment by katieefrey** [comment]
accepted, will see in next release.
