### ISSUE TITLE
New Concept: Surface ices

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#308]
Entering this as its own ticket as I expect there may be some back and forth.

STScI Planetary researchers proposed new term to summarize concept of: "Outer solar system satellites and minor bodies covered with ices that can be studied via spectroscopy."

Hierarchy proposed is as follows:
Solar systems astronomy
...Planetary science
......Planetary structure
.........Planetary surfaces (proposed new term, ticket #303)
............Surface ices 
(or "Surface ice" if plural seems odd; literature is split between singular and plural forms depending on context)

Supporting literature:
https://ui.adsabs.harvard.edu/abs/2019JGRE..124..243M/abstract
https://ui.adsabs.harvard.edu/abs/2018AGUFM.P51E2931W/abstract
https://ui.adsabs.harvard.edu/abs/2018AJ....155..170S/abstract
https://ui.adsabs.harvard.edu/abs/2016DPS....4840703S/abstract
https://ui.adsabs.harvard.edu/abs/2015ApJ...812..150M/abstract

**Comment by katieefrey** [comment]
In general the concept looks fine, will be included.  Will probably go with the plural "ices" since pluralizing is preferred in general, unless a concept should specifically be singular.

See also #304

**Comment by katieefrey** [comment]
Accepted, implemented, will be in the next version!
