### ISSUE TITLE
New Concepts: a number of concepts in Gravitational microlensing

### ISSUE THREAD

**Issue by rpoleski** [astrothesaurus/UAT#310]
**Name the new concept**
We propose the following structure:

Gravitational microlensing|Gravitational microlensing planet detection
Gravitational microlensing|Quasar microlensing
Gravitational microlensing|Multi-lens microlensing
Gravitational microlensing|Multi-lens microlensing|Binary lens microlensing
Gravitational microlensing|Multi-lens microlensing|Triple lens microlensing
Gravitational microlensing|Multi-lens microlensing|Caustic curve
Gravitational microlensing|Multi-lens microlensing|Critical curve
Gravitational microlensing|Multi-lens microlensing|Lens orbital motion
Gravitational microlensing|Microlensing parallax
Gravitational microlensing|Microlensing parallax|Satellite microlensing parallax
Gravitational microlensing|Microlensing parallax|Annual microlensing parallax
Gravitational microlensing|Microlensing parallax|Topocentric microlensing parallax
Gravitational microlensing|Single lens microlensing
Gravitational microlensing|Single lens microlensing|Free floating planets
Gravitational microlensing|High-resolution microlensing event imaging
Gravitational microlensing|Stellar remnant microlensing
Gravitational microlensing|Optical depth
Gravitational microlensing|Microlensing event rate
Gravitational microlensing|Astrometric microlensing effect
Gravitational microlensing|Single source microlensing
Gravitational microlensing|Binary source microlensing
Gravitational microlensing|Binary source microlensing|Xallarap effect
Gravitational microlensing|Massive astrophysical compact halo objects
Gravitational microlensing|Photometric microlensing effect
Gravitational microlensing|Photometric microlensing effect|Finite-source photometric effect
Gravitational microlensing|Photometric microlensing effect|Magnification
Gravitational microlensing|Einstein ring
Gravitational microlensing|Einstein ring|Einstein ring radius
Gravitational microlensing|Einstein ring|Einstein ring radius|Einstein ring radius crossing time

**Describe the concept**
Descriptions will be added in this thread soon.

**Describe where the concept fits within the existing hierarchy**
Full hierarchy is presented

**Provide 1-3 supporting articles**
References will be added in this thread soon.

**Please include any additional comments/feedback**
First two lines show changes proposed earlier. The rest of lines are sorted according to importance of adding second column term to UAT.
Different microlensing parallax types have alternative names that may be confusing:
1) annual – orbital;
2) topocentric – terrestial, geocentric.

"Massive astrophysical compact halo objects" or "Massive compact halo objects" are frequently abbreviated as "MACHOs".

This post was prepared by Radek Poleski (@rpoleski) and Rachel Street (@rachel3834).

**Comment by katieefrey** [comment]
@rpoleski @rachel3834

Jennifer Yee stopped by yesterday afternoon to ask some questions about the UAT structure related to these suggestions, but I don't think she's had a chance to follow up with you quite yet.

The main thing that stood out to me when looking at this yesterday was that concepts like "free floating planets", "stellar remnants", and "machos" are things that are found using microlensing, but aren't themselves microlensing, so they don't fit well under this hierarchy.  FFP is already a concept in the UAT that currently has a "related term" link to microlensing.  I can add "related term" link for "stellar remnants" as well.  "MACHOs" do not currently exist in the UAT, so they would have to be added somewhere else and then linked as a related term.  When I spoke briefly with Jennifer yesterday, she said MACHOs would fit somewhere under "Dark matter."

Jennifer had some additional things that she noted, so I'm hoping she can jump in with her thoughts.

**Comment by rpoleski** [comment]
I hope Jennifer will post her propositions here.

When it comes to FFP and similar concepts, it's not clear for me when to use "related term" and when to put the same term twice in different places of hierarchy. Are there any guidelines on that?

**Comment by rpoleski** [comment]
Supporting references:

Binary lens microlensing
[1993A%26A...268..453E Erdl & Schneider 1993](https://ui.adsabs.harvard.edu/abs/1993A%26A...268..453E/abstract)
[1995ApJ...447L.105W Witt & Mao 1995](https://ui.adsabs.harvard.edu/abs/1995ApJ...447L.105W/abstract)

Triple lens microlensing
[2008Sci...319..927G Gaudi et al. 2008](https://ui.adsabs.harvard.edu/abs/2008Sci...319..927G/abstract)
[2002ApJ...580..490H Han & Han 2002](https://ui.adsabs.harvard.edu/abs/2002ApJ...580..490H/abstract)
[2014ApJ...788...73Z Zhu et al. 2014](https://ui.adsabs.harvard.edu/abs/2014ApJ...788...73Z/abstract)

Microlensing parallax
[1995ApJ...447...53H Han & Gould 1995](https://ui.adsabs.harvard.edu/abs/1995ApJ...447...53H/abstract)
[2000ApJ...542..785G Gould 2000](https://ui.adsabs.harvard.edu/abs/2000ApJ...542..785G/abstract)

Satellite microlensing parallax
[1996ApJ...462..705B Boutreux & Gould 1996](https://ui.adsabs.harvard.edu/abs/1996ApJ...462..705B/abstract)
[1995ApJ...441L..21G Gould 1995](https://ui.adsabs.harvard.edu/abs/1995ApJ...441L..21G/abstract)

Annual microlensing parallax
[1999A%26A...350L..19M Mao 1999](https://ui.adsabs.harvard.edu/abs/1999A%26A...350L..19M/abstract)
[2001ApJ...552..731S Soszynski et al. 2001](https://ui.adsabs.harvard.edu/abs/2001ApJ...552..731S/abstract)
[1995ApJ...454L.125A Alcock et al. 1995](https://ui.adsabs.harvard.edu/abs/1995ApJ...454L.125A/abstract)

Topocentric microlensing parallax
[2014Sci...345...46G Gould et al. 2014](https://ui.adsabs.harvard.edu/abs/2014Sci...345...46G/abstract)
[2013ApJ...764..107G Gould & Yee 2013](https://ui.adsabs.harvard.edu/abs/2013ApJ...764..107G/abstract)
[2009ApJ...698L.147G Gould et al. 2009](https://ui.adsabs.harvard.edu/abs/2009ApJ...698L.147G/abstract)

High-resolution microlensing event imaging
[2015ApJ...808..170B Batista et al. 2015](https://ui.adsabs.harvard.edu/abs/2015ApJ...808..170B/abstract)
[2015ApJ...808..169B Bennett et al. 2015](https://ui.adsabs.harvard.edu/abs/2015ApJ...808..169B/abstract)
[2007ApJ...671..420K Kozlowski et al. 2007](https://ui.adsabs.harvard.edu/abs/2007ApJ...671..420K/abstract)

Optical depth
[2019ApJS..244...29M Mroz et al. 2019](https://ui.adsabs.harvard.edu/abs/2019ApJS..244...29M/abstract)
[2003ApJ...592..172H Han & Gould 2003](https://ui.adsabs.harvard.edu/abs/2003ApJ...592..172H/abstract)

Microlensing event rate
[2019ApJS..244...29M Mroz et al. 2019](https://ui.adsabs.harvard.edu/abs/2019ApJS..244...29M/abstract)
[2009MNRAS.396.1202K Kerins, Robin & Marshall 2009](https://ui.adsabs.harvard.edu/abs/2009MNRAS.396.1202K/abstract)

Astrometric microlensing effect
[2017Sci...356.1046S Sahu et al. 2017](https://ui.adsabs.harvard.edu/abs/2017Sci...356.1046S/abstract)
[1995A%26A...294..287H Hog, Novikov & Polnarev 1995](https://ui.adsabs.harvard.edu/abs/1995A%26A...294..287H/abstract)
[2018AcA....68..183B Bramich & Nielsen 2018](https://ui.adsabs.harvard.edu/abs/2018AcA....68..183B/abstract)

Binary source microlensing
[1992ApJ...397..362G Griest & Hu 1992](https://ui.adsabs.harvard.edu/abs/1992ApJ...397..362G/abstract)
[1998ApJ...506..533G Gaudi 1998](https://ui.adsabs.harvard.edu/abs/1992ApJ...397..362G/abstract)
[1998MNRAS.301..231H Han & Jeong 1998](https://ui.adsabs.harvard.edu/abs/1998MNRAS.301..231H/abstract)

Xallarap effect
[1992ApJ...397..362G Griest & Hu 1992](https://ui.adsabs.harvard.edu/abs/1992ApJ...397..362G/abstract)
[2005ApJ...633..914P Poindexter et al. 2005](https://ui.adsabs.harvard.edu/abs/2005ApJ...633..914P/abstract)

Massive astrophysical compact halo objects
[1992ApJ...392..442G Gould 1992](https://ui.adsabs.harvard.edu/abs/1992ApJ...392..442G/abstract)
[2011MNRAS.416.2949W Wyrzykowski et al. 2011](https://ui.adsabs.harvard.edu/abs/2011MNRAS.416.2949W/abstract)

**Comment by katieefrey** [comment]
@rpoleski 
Sorry for my delay in getting to this, something came up yesterday which needed immediate attention.

> When it comes to FFP and similar concepts, it's not clear for me when to use "related term" and when to put the same term twice in different places of hierarchy. Are there any guidelines on that?

The hierarchical relationships used in the UAT follow the guidelines in the ANSI/NISO z39.19 standard ([freely available here](https://groups.niso.org/apps/group_public/download.php/12591/z39-19-2005r2010.pdf)) and the ISO 25964 standard ([NOT available freely](https://www.iso.org/standard/53657.html), but is similar on this topic).

Essentially there are three types of hierarchical relationship:
a) the generic relationship
b) the instance relationship
c) the whole-part relationship

Type a) is a relationship between a class and its members.  A "Solar x-ray flare" is a type of "Solar flare."

Type b) is usually described by a generic category and a specific example of that category.  "Space observatories" is a category and one of it's children, "Hubble Space Telescope" is a specific example of the category.

Type c) involves a situation where one concept is inherently included in another, regardless of context. "Interstellar plasma" is a part of the "Interstellar medium." 

In the case of FFPs, FFPs are not a type of "Single lens microlensing," they are not an example of "Single lens microlensing," and they are not a part of "Single lens microlensing."

Instead the relationship is more complicated: FFPs are something that can be discovered using "Single lens microlensing."  They are an example of something that can be found using Single lens microlensing, but they aren't an example of microlensing itself.

In a thesaurus, which is how the UAT is structured, the way to capture these relationships is by using the "related term" connector.  I'm sure the UAT doesn't follow these guidelines perfectly; sometimes I find that having the concept somewhere now is more important then placing it perfectly (at least in the short term), but I do strive to follow the guidelines as best as possible.

**Comment by rpoleski** [comment]
I've tried to combine the structure proposed above with Jen Yee suggestions. I've came up with:

Gravitational microlensing|Gravitational microlensing planet detection
Gravitational microlensing|Quasar microlensing
Gravitational microlensing|Binary lens microlensing
Gravitational microlensing|Triple lens microlensing
Gravitational microlensing|Caustic curve
Gravitational microlensing|Critical curve
Gravitational microlensing|Lens orbital motion
Gravitational microlensing|Microlensing parallax
Gravitational microlensing|Microlensing parallax|Satellite microlensing parallax
Gravitational microlensing|Microlensing parallax|Annual microlensing parallax
Gravitational microlensing|Microlensing parallax|Topocentric microlensing parallax
Gravitational microlensing|High-resolution microlensing event imaging
Gravitational microlensing|Optical depth
Gravitational microlensing|Microlensing event rate
Gravitational microlensing|Astrometric microlensing effect
Gravitational microlensing|Binary source microlensing
Gravitational microlensing|Binary source microlensing|Xallarap effect
Gravitational microlensing|Finite-source photometric effect
Gravitational microlensing|Einstein ring

**Comment by katieefrey** [comment]
Hi Radek,

Thanks for taking another pass at this.  I've spent the better part of today thinking about these concepts, how they would fit in the UAT, and reviewing a few points of thesauri best practices.   I think over all these concepts look good, and I have a few questions:

1) Are "caustic curve" and "critical curve" specific to microlensing, or do they also apply to "gravitational lensing"? What about "Lens orbital motion"?

2) Is there a relationship between "caustic crossing" (which already exists in the UAT, as a child of "gravitational lensing") and "caustic curve"?

3) A couple of things regarding the four parallax terms:
a) Would it be sufficient to use two concepts to convey most of these, such as "Annual parallax" and "Gravitational microlensing"?   (Astrometry|Parallax|Annual parallax already exists, I would add Satellite parallax and Topocentric parallax to the same location)

b) If having a single term is greatly preferred, what would you say to moving them to Astrometry->Parallax and connecting them back to gravitational microlensing with an RT?  (either all 4 can RT or just the parent "microlensing parallax")

Astrometry|Parallax|Microlensing parallax   [RT: Gravitational microlensing]
Astrometry|Parallax|Microlensing parallax|Satellite microlensing parallax
Astrometry|Parallax|Microlensing parallax|Annual microlensing parallax
Astrometry|Parallax|Microlensing parallax|Topocentric microlensing parallax

4) I recommend changing "Optical depth" to "Microlensing optical depth"; language I saw in both of your support articles.

**Comment by rpoleski** [comment]
1. Yes, all these terms make sense for "gravitational lensing" as well. I think "lens orbital motion" is very rarely used for lensing. 
2. Yes. "Caustic crossing" happens when source crosses the caustic curve.
3. First, to clarify: microlensing parallax is a vector of length equal to lens parallax minus source parallax and divided by the Einstein ring radius. The direction of this vector is the same as proper motion of lens minus proper motion of source. The "Astrometry|Parallax" is a scalar, not a vector. Microlensing parallax makes sense only when we have a microlensing event. In my opinion, very rarely there are papers that would use both "Astrometry|Parallax" and "Gravitational microlensing|Microlensing parallax" as keywords.
3.a. I'm against such a change. The "Astrometry|Parallax" is detected in astrometric measurements, but all types of "Microlensing parallax" are detected in photometric measurements (in great majority of cases). 
3.b. For me, the microlensing parallax is related to "Parallax" but really quite different, so once more I'm against.
4. Ok.

Maybe @rachel3834 can comment on these points.

**Comment by katieefrey** [comment]
Thank you!  Alright, this is where I'm at:

Gravitational lensing|Gravitational microlensing|Gravitational microlensing planet detection
Gravitational lensing|Gravitational microlensing|Quasar microlensing
Gravitational lensing|Gravitational microlensing|Binary lens microlensing
Gravitational lensing|Gravitational microlensing|Triple lens microlensing
Gravitational lensing|Gravitational microlensing|High-resolution microlensing event imaging
Gravitational lensing|Gravitational microlensing|Microlensing optical depth
Gravitational lensing|Gravitational microlensing|Microlensing event rate
Gravitational lensing|Gravitational microlensing|Astrometric microlensing effect
Gravitational lensing|Gravitational microlensing|Binary source microlensing
Gravitational lensing|Gravitational microlensing|Binary source microlensing|Xallarap effect
Gravitational lensing|Gravitational microlensing|Finite-source photometric effect
Gravitational lensing|Gravitational microlensing|Lens orbital motion
Gravitational lensing|Gravitational microlensing|Microlensing parallax   [RT: Parallax]
Gravitational lensing|Gravitational microlensing|Microlensing parallax|Satellite microlensing parallax
Gravitational lensing|Gravitational microlensing|Microlensing parallax|Annual microlensing parallax
Gravitational lensing|Gravitational microlensing|Microlensing parallax|Topocentric microlensing parallax
Gravitational lensing|Gravitational microlensing     [RT: Free Floating Planets]
Gravitational lensing|Einstein ring
Gravitational lensing|Caustic curve
Gravitational lensing|Caustic crossing
Gravitational lensing|Critical curve
(Let me know if you do not have a strong preference for the following 4 relationships, because having these as children of Gravitational lensing makes these a bit redundant.)
Gravitational lensing|Gravitational microlensing|Caustic curve
Gravitational lensing|Gravitational microlensing|Caustic crossing
Gravitational lensing|Gravitational microlensing|Critical curve
Gravitational lensing|Gravitational microlensing|Einstein ring

**Comment by rpoleski** [comment]
I'm fine with having the last four terms under Gravitational lensing. 

The only remaining comment I have is that there is no Caustic crossing without Caustic curve, so maybe the former could be a child of the latter.

**Comment by katieefrey** [comment]
Great!  Implemented as follows, will be in the next release.

Gravitational lensing|Gravitational microlensing|Gravitational microlensing planet detection
Gravitational lensing|Gravitational microlensing|Quasar microlensing
Gravitational lensing|Gravitational microlensing|Binary lens microlensing
Gravitational lensing|Gravitational microlensing|Triple lens microlensing
Gravitational lensing|Gravitational microlensing|High-resolution microlensing event imaging
Gravitational lensing|Gravitational microlensing|Microlensing optical depth
Gravitational lensing|Gravitational microlensing|Microlensing event rate
Gravitational lensing|Gravitational microlensing|Astrometric microlensing effect
Gravitational lensing|Gravitational microlensing|Binary source microlensing
Gravitational lensing|Gravitational microlensing|Binary source microlensing|Xallarap effect
Gravitational lensing|Gravitational microlensing|Finite-source photometric effect
Gravitational lensing|Gravitational microlensing|Lens orbital motion
Gravitational lensing|Gravitational microlensing|Microlensing parallax [RT: Parallax]
Gravitational lensing|Gravitational microlensing|Microlensing parallax|Satellite microlensing parallax
Gravitational lensing|Gravitational microlensing|Microlensing parallax|Annual microlensing parallax
Gravitational lensing|Gravitational microlensing|Microlensing parallax|Topocentric microlensing parallax
Gravitational lensing|Gravitational microlensing [RT: Free Floating Planets]
Gravitational lensing|Einstein ring
Gravitational lensing|Caustic curve
Gravitational lensing|Caustic curve|Caustic crossing
Gravitational lensing|Critical curve
