### ISSUE TITLE
New Concept: [additional waveband and spectroscopy concepts]

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#319]
**Describe the new concepts**
The UAT has "Radio spectroscopy," but no "Optical spectroscopy" (or any other waveband spectroscopy).  Various wavebands should probably have specific spectroscopy concepts too.

Other related waveband issue...
The UAT has "Near ultraviolet astronomy," and "Solar extreme ultraviolet emission," but no general concept for "Extreme ultravioletastronomy."

**Describe where the concept fits within the existing hierarchy**
These concepts should be found under their waveband type of astronomy ("Radio astronomy," "Gamma-ray astronomy," "Visible astronomy," etc...).  They should also probably be under the general "Spectroscopy" concept.  Currently Radio astronomy is not found a child of "Spectroscopy."

**Please include any additional comments/feedback**
Comment suggested by Markus Demleitner as part of his work mapping IVOA and UAT concepts.

**Comment by katieefrey** [comment]
Over 4k hits for a title only search of ADS for "extreme ultraviolet," adding this as child of "ultraviolet astronomy."

Radio spectroscopy moved to child of spectroscopy.  I also added a RT back to Radio astronomy, but I could also leave it as a child of "radio astronomy" instead? That might be the best idea, though it sort of breaks my psudeo-definition for "astronomy methods."

Can add optical spectroscopy and x-ray spectroscopy as children of spectroscopy as well, with RT back to their relevant branch of astronomy.  Gamma-ray, infrared, and ultraviolet too?

@msdemlei

**Comment by msdemlei** [comment]
On Wed, Oct 21, 2020 at 01:07:32PM -0700, Katie Frey wrote:
> Can add optical spectroscopy and x-ray spectroscopy as children of
> spectroscopy as well, with RT back to their relevant branch of
> astronomy.  Gamma-ray, infrared, and ultraviolet too?

From a VO perspective I'm not a big fan of having a large number of
per-waveband concepts; in VOResource, we have a separate piece of
metadata that says what waveband something is for, and even in a pure
UAT environment I guess spectroscopy and x-ray-astronomy together
aren't much worse than x-ray-spectroscopy (or are they?  Now that I
think of it that suddenly isn't all that clear to me any more, as
composition rules for concepts actually require definition...)

So, I'd wait.  Do we understand where radio-spectroscopy came from?
And why they didn't bother to talk about spectroscopy in other
wavebands?

**Comment by katieefrey** [comment]
Radio spectroscopy is in the [IAU Thesaurus](http://www.mso.anu.edu.au/library/thesaurus/english/RADIOSPECTROSCOPY.html).

IAU Thesaurus also has...

- absorption spectroscopy
- collision spectroscopy
- fourier transform spectroscopy
- gamma ray spectroscopy
- high resolution spectrosopy [sic]
- interference spectrosocopy [sic]
- microwave spectroscopy
- optical spectroscopy
- raman spectroscopy
- time resolved spectroscopy
- two dimensional spectroscopy
- x ray spectroscopy

See: http://www.mso.anu.edu.au/library/thesaurus/english/SPECTROSCOPY.html

No idea why these other concepts were not ported into the UAT originally.

That being said, I also am not a huge fan of adding specific wavelength concepts for everything (though there already are a lot).  Using a pair of concepts together is nicer, imo, but I could go either way with these.

**Comment by katieefrey** [comment]
Not adding these for now, but open to adding them in the future if there is a call to do so.
