### ISSUE TITLE
Possible duplicate concepts surrounding optical/visible astronomy

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#320]
These concepts seem to have similar meanings.  What are the distinctions between them? Should they be merged?

Optical observation
Visible astronomy
Visual observation 

Reconsider the relationships (child, parent, related) between the following concepts and the above concepts? 
Optical interferometry
Optical identification
Optical observatories
Optical flares
Optical bursts
Optical double stars
Optical phase shifting interferometry 
Optical position
Optical pulsars 
Optical telescopes
Solar optical telescopes
Visible sources
[others?]

Comment originated with Markus Demleitner as part of his work mapping IVOA and UAT concepts.

**Comment by katieefrey** [comment]
I think optical and visual observation are possibly the same thing.  Or perhaps one is with optical instruments and the other is observing with the naked eye?  However, I don't think it's super valuable to have a concept about naked eye observations.

Looking at the context for these concepts....
Optical observation is listed as a technique.  And that makes some sense to me.  Just looking at a thing with your eye (with or without a telescope) can give you some information.

Visible astronomy is under methods, which I like because the "methods" section is all about different wavelengths of astronomy (radio astronomy, xray astronomy etc).  However it might be better to call it "Optical astronomy"?  I like sticking with words like "visible" or "visual" to describe a wavelength range, and not optical because even x-ray telescopes use optics to make their measurements.

Visual observation is also under methods... but I think its mostly a duplicate of visible astronomy.  Unlike the other two, visual observation actually has CHILD concepts:
Center to limb observation
Limb brightening
Limb darkening
Optical double stars
Optical identification
Zenith hourly rate

Methods about wavelengths and effects of observing at different wavelengths, and techniques is more about things you do with instruments to observe those wavelengths (photometry, spectroscopy, etc).

I'm inclined to merge optical observation and visual observation, and put them under techniques, probably using "Visual observation" as the preferred concept.  The eye (with or without a telescope) is an instrument used to observe the visual wavelengths.

As for the child concepts, if I look at my above definitions, all describe effects of observing in visual wavelengths, and therefore fit better under "methods" > "visual astronomy".

**Comment by katieefrey** [comment]
Also... "Astronomical optics" under techniques...
hmm "extinction" and " dark adaption" can be found here,  would limb darkening/brightening be a good fit here as well? perhaps some of the other child concepts above as well?

Tagging @msdemlei since I already sent a follow up email on this.

**Comment by msdemlei** [comment]
When doing this kind of thing, I tend to first try to write the
definitions and then see if there's a nice label of it.  So, in the
current case, I think there are to concepts involved:

  (A) Astronomy using visible light (400 .. 800 nm) as the messenger

and

  (B) Astronomy using the (human) eye as the primary detector; this
  includes both naked-eye observations and observations through
  telescopes without further instrumentation (like cameras,
  spectrographs, and the like).

Ignoring the question if solar observations using screens would fall
under (B): Would you (in particular @katiefrey) roughly agree with that
systematics?

If so, then I'd call (A) optical-astronomy.  You're right that there is
x-ray "optics", but I think most other terminology in the UAT is that
the waveband is called "Optical", not "Visible".  The second concept I'd
call visual-observation (with a proviso that when there's sufficient
interest we could have a narrower of naked-eye-observation one day).

What the current visible-astronomy once was supposed to be I can't
really say.  As long as we don't have a good definition for it, I
personally would probably deprecate it (and visible-sources with it).
But perhaps we shouldn't rush it.  Do we know where it came from?

The downside of this plan is that the narrowers of visual-observation
don't make too much sense any more.  I'm really at a loss how limb-* got
in there.  optical-identification would probably need to go to
optical-astronomy.

optical-double-stars... hm -- are these double stars that can be
resolved as opposed to eclipsing or spectroscopic binaries)?  Then I'd
say they should go to neither concept, the "optical" being a red herring
(you could just as well resolve them in the infrared or even UV these
days).  If, indeed, the few double stars resolvable with the naked eye
are meant, we should change the preferred label.

zenith-hourly-rate, then... well, that may be the most plausible
"visual-observation" of the current narrowers, but even there I strongly
suspect that most actual ZHR measurements are now done by machines,
either fisheye cameras or perhaps even radar devices.

So: Suddenly all the narrowers of visual-observations would be gone,
which is an indication we might have changed the meaning of the concept
(which would be bad).  But then I have a hard time finding a common
wider concept of visual-observation's current narrowers, so perhaps the
concept wasn't defined well enough before to know whether we've changed
it...

**Comment by katieefrey** [comment]
Yes, I think your A and B definitions match the two main concepts here.

"Visible astronomy" comes from UAT Beta.  I cannot find it in IVOA or IAU Thesauri.  It is likely this concept comes from the third party company.

"optical double stars" has a scope note for clarification (but it should have a proper definition): "Use only for pair in chance alignment"
So, "optical doubles" are stars that look like a they are a binary pair when observed visually, but are actually not related at all.
This is in contrast to "visual binary stars," which are binary stars that can also be visually resolved as two stars with your eye (and telescope).
Both "optical doubles" and "visual binary stars" exist as separate concepts in the IAU and IVOA thesauri, with a similar scope note.

"optical double stars", "limb darkening," "limb brightening," "zenith hourly rate," and "optical identification" all existed in UAT Beta, as child concepts of "Observational astronomy."   They were moved to "Visual observation" sometime between July and Dec 2015, ahead of the v1.0.0 release.  I can't pinpoint the reason for the change in my files at the moment.  I might have something on it somewhere, but there were a LOT of changes happening at that time...

"center to limb observations" was added at v3.0.0 during my work with Amiee Norton (#115).  The new concept was added to this location because the other limb-related concepts were found here already.

**Comment by katieefrey** [comment]
I propose to:

Rename http://astrothesaurus.org/uat/1776 (Visible astronomy) to "Optical astronomy"
working definition: Astronomy using visible light (400 .. 800 nm) as the messenger.
Even though visible astronomy was the concept you least liked, to my mind it has the same meaning as the new "Optical astronomy," making this the right candidate for renaming.

Move http://astrothesaurus.org/uat/1778 (Visual observation) to "techniques"
working definition:  Astronomy using the (human) eye as the primary detector; this includes both naked-eye observations and observations through telescopes without further instrumentation (like cameras, spectrographs, and the like).
Keeping the same concept, but moving it from methods to techniques.

What about http://astrothesaurus.org/uat/1169 ("Optical observation") ?  In IVOAT, "optical observation" has RT "optical observatory."  THAT concept has RT "optical telescope."  This feels like observation with... a telescope?  1169 might be a candidate for deprecation, but concepts that originate from IVOA and IAU thesauri are usually worth thinking about.

Now for the rest of those child concepts...  If the child concepts don't with with "Visual observation," I think that's mostly because we have examined how poorly these concepts fit with it in the first place, rather than making drastic changes to "visual observation" as a concept.

You identified that "Optical identification" fits well with "Optical astronomy."

I think "optical doubles" fits with "visual observation," it's literally an optical effect from look at two stars visually.

Limb dark/bright is related to apparent or observed phenomena of the sun and stars.
[Darkening](http://dictionary.obspm.fr/index.php?formSearchTextfield=limb+darkening&formSubmit=Search&showAll=1) is in the optical range, but [brightening](http://dictionary.obspm.fr/index.php?formSearchTextfield=limb+brightening&formSubmit=Search&showAll=1) is in radio, EUV, and x-rays.  Darkening _might_ fit somewhere with Optical astronomy, but I don't think brightening does (or ever did).

I believe "Center to limb observations" is the act of making observations about limb darkening or brightening.

Maybe we need a "solar observation" concept to group these three somewhere..?  However, this limb effect is seen in stars too, ok, so bad idea.

Zenith hourly rate is related to meteor showers.. maybe it fits with "Optical astronomy" as something observed in the optical spectrum?  It's not a great fit though.

**Comment by msdemlei** [comment]
On Thu, Oct 22, 2020 at 02:37:21PM -0700, Katie Frey wrote:
> I think "optical doubles" fits with "visual observation," it's
> literally an optical effect from look at two stars visually.

Hm... but establishing optical-double-stars happens generally through
fairly complicated procedures (either proper motion determination or
perhaps through spectroscopic parallax or so); so, to me it feels
wrong to associate it with a visual-observation.

I still don't understand enough of the systematics of UAT to suggest
a better place for the concept, though.  Perhaps there is a concept
somewhere in the vicinitiy of "Phenomena we only see because we're on
earth" (which could include parallax, aberration, epicycles, and
perhaps observed photometry)?

> Limb dark/bright is related to apparent or observed phenomena of the sun and stars.
> [Darkening](http://dictionary.obspm.fr/index.php?formSearchTextfield=limb+darkening&formSubmit=Search&showAll=1) is in the optical range, but [brightening](http://dictionary.obspm.fr/index.php?formSearchTextfield=limb+brightening&formSubmit=Search&showAll=1) is in radio, EUV, and x-rays.  Darkening _might_ fit somewhere with Optical astronomy, but I don't think brightening does (or ever did).

No, all this isn't dependent on the wavelength of the observation.
It's a deeply physical phenomenon.  I'd make it narrower than
solar-atmosphere and perhaps stellar-atmospheres.

> I believe "Center to limb observations" is the act of making
> observations about limb darkening or brightening.

Hm.  Not sure about that.  Should I ask solar physics people if they
can provide a nice definition?

Anyway, that's something that I believe we won't see of non-solar
stars for quite a while, so I'd just move it to solar-atmosphere as
well (if there was solar-observations, I'd choose that).

> Zenith hourly rate is related to meteor showers.. maybe it fits
> with "Optical astronomy" as something observed in the optical
> spectrum?  It's not a great fit though.

As I said, I believe what professional ZHR data is being obtained at
all these days probably uses radio because it works through clouds
and even during the day.

My choice would be: Make it narrower than meteors.

**Comment by katieefrey** [comment]
Renamed http://astrothesaurus.org/uat/1776 (Visible astronomy) to "Optical astronomy"
Moved http://astrothesaurus.org/uat/1778 (Visual observation) to "techniques"

Limb bright/dark-ening moved to "Solar atmospheres"

ZHR moved to "meteor showers," as the definition specifies showers...

**Comment by katieefrey** [comment]
http://astrothesaurus.org/uat/1169 ("Optical observation") is still a question.

What differentiates it from "visual observation"?  I'm leaning towards deprecating 1169 as a duplicate concept.

@msdemlei I missed it earlier, but yea, if you have a solar physicist you can reach out to regarding "center to limb observations," please do!

**Comment by katieefrey** [comment]
Looking at this again, 1169 ("Optical observation") has resonated more with users (10 uses as a keyword in ADS) than 1778 ("Visual observation") (with 0 uses).
Going to merge 1778 into 1169, and keep the pref label as "Optical Observation."
