### ISSUE TITLE
Modify Concept: Algol variable stars vs Eclipsing binary stars ?

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#324]
**Name the concept in question**
Algol variable stars vs Eclipsing binary stars

**Describe the change**
According to the Etymological Dictionary of Astronomy and Astrophysics, these concepts are synonymous 
http://dictionary.obspm.fr/index.php?showAll=1&formSearchTextfield=Algol

**Comment by rpoleski** [comment]
I don't agree with that change. See [GCVS definition](http://www.sai.msu.su/gcvs/gcvs/vartype.htm) of "EA Algol" or [wikipedia page](https://en.wikipedia.org/wiki/Algol_variable).

**Comment by katieefrey** [comment]
Thanks for the fast feedback on this!  I was really surprised when I saw the definition of Algol-type variables was "The same as eclipsing binary stars, the prototype of which is Algol."
