### ISSUE TITLE
New Concept: Extrasolar gaseous planets

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#328]
Extrasolar gaseous planets

A concept more broad than Extrasolar gas giants, which is being proposed as a child term. Exoplanet researchers suggested too much uncertainty to state and compare all gas planets to gas giants in Exo community.

Proposed hierarchy:
Exoplanet astronomy-->Exoplanets-->Extrasolar gaseous planets (with NPT: Extrasolar gas planets)--> Extrasolar gaseous giants (with NPT: Extrasolar gas giants).

Provides same broad concept as "Extrasolar rocky planets" which is not defined by size but by composition (and then perhaps by size in future).

2020AAS...23523802L
2019AAS...23310505M
List bibcodes or other identifiers for articles that support the need for this new concept in the literature.

Related to ST keyword enhancements.

**Comment by katieefrey** [comment]
Also dovetails with feedback from #334.

this change has been implemented
Exoplanet astronomy-->Exoplanets-->Extrasolar gaseous planets (with NPT: Extrasolar gas planets)--> Extrasolar gaseous giants (with NPT: Extrasolar gas giants)
