### ISSUE TITLE
New Concept: Star-planet interactions

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#329]
Star-planet interactions

Equivalent term for "Space weather" under Solar system astronomy, only more appropriate term to describe in exoplanet science. 

UAT Hierarchy proposed: Exoplanet astronomy--> Exoplanet dynamics--> Star-planet interactions. 

For now, until I have more feedback from ST scientists, propose to keep "Exoplanet tides" at same level as "Star-planet interactions". At some point may propose as child term to "Star-planet interactions" in new ticket.

2020MNRAS.497.1015F
2020IAUS..354..295A
"star-planet interaction" widely used in literature in reference to exoplanets.
https://ui.adsabs.harvard.edu/search/q=%22star-planet%20interactions%22&sort=date%20desc%2C%20bibcode%20desc&p_=0

Part of ST keyword enhancements.

**Comment by katieefrey** [comment]
In general, I think this concept makes sense to add to the UAT, and I will add it where proposed.

However, this spawned two related comments/questions for further discussion, which I will split off into a separate ticket for further contemplation.  See #335

**Comment by katieefrey** [comment]
I guess "star-exoplanet interactions" would be too clunky, eh?  It's more in keeping with the wording....  Well, adding it as an NPT at the very least.
