### ISSUE TITLE
New Concept: Galactic Archaeology

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#330]
Galactic Archaeology (weird misnomer but definitely should be placed under Stellar astronomy and probably also Galaxies)

Brief definition: Study of galactic evolution through study of stellar populations.
https://www.aao.gov.au/public/galactic-archaeology

Proposed hierarchies:
Stellar astronomy --> Galactic archaeology
Galactic and extragalactic astronomy --> Galaxy physics --> Galactic archaeology

Proposed related term (RT): Asteroseismology

2017A&A...601A..27L
2019A&A...623A..60S
2013MNRAS.436.1362Y

I am struggling with exact placement or placements in the UAT hierarchy but I agree this is a unique concept that does not seem to be captured yet in the vocabulary.

ST keyword enhnacements

**Comment by katieefrey** [comment]
Is this concept focused on or limited to the Milky Way Galaxy?

**Comment by katieefrey** [comment]
Answering my own question it looks like this subject is almost always about the Milky Way.  I did find at least one article that applied it more generally, but it was also looking at chemical abundances instead of stellar populations.

**Comment by katieefrey** [comment]
I've added this concept in these two places:

Stellar astronomy --> Galactic archaeology
Galactic and extragalactic astronomy --> Galaxy physics --> Milky Way Galaxy physics --> Galactic archaeology

Like you said, it's hard to really determine the best placement.  I think this will be fine for now, and we can move it later if this doesn't turn out to be the most intuitive location.
