### ISSUE TITLE
Modify Concept: Low surface brightness galaxies

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#331]
Low surface brightness galaxies
http://astrothesaurus.org/uat/940

Parent term "Low surface brightness galaxies" should not be changed, but should be enhanced with more NPTs as follows:
 "ultra-diffuse galaxies"
"ultradiffuse galaxies"
"ultra diffuse galaxies"
UDG

Searches for all of the above exact forms yields results in ADS and as far as I can gather from researchers in the field it is synonymous with LSBG

**Comment by katieefrey** [comment]
Added alternate labels
