### ISSUE TITLE
New Concept: Post-starburst galaxies

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#332]
Post-starburst galaxies

General definition: galaxies that have only recently stopped forming stars
https://astrobites.org/2018/02/01/post-starburst-galaxies-the-missing-link-in-galaxy-evolution/

Galactic and extragalactic astronomy--> Galaxies --> Post-starburst galaxies

Exact verbiage from ST research staff to support hierarchy placements:
"I believe that I hope to have post-starburst galaxies to be a distinct category of galaxies."
Child term: "E+A galaxies would be BOTH post-starburst galaxies and would be early-type galaxies" (where E+A already sits in UAT; relates to next GitHub issue on E+A)

2020ApJ...900..107Y 
2020MNRAS.494..529W 
2020MNRAS.498.1259Z

ST keyword enhancement

**Comment by katieefrey** [comment]
Some additional supporting articles I found looking into this:

2009MNRAS.397.1940F "...we find that the common E+A criteria exclude a significant number of post-starburst galaxies..."

2009MNRAS.397.1954F "...the classical definition of E+A galaxies excludes a significant number of post-starburst galaxies..."

2020AAS...23525802G "this E+A sample, assembled with these refined criteria to establish a well-defined population within the broader post-starburst galaxy population..."

Based on these and the above, I'm adding PSBs and setting E+A as a child concept (per #333)
