### ISSUE TITLE
Modify Concept: E+A galaxies

### ISSUE THREAD

**Issue by stlibrary8** [astrothesaurus/UAT#333]
E+A galaxies
http://astrothesaurus.org/uat/424 

Request to place E+A galaxies as child term to newly proposed "Post-starburst galaxies" in addition to existing (and also correct placement) under "Early-type galaxies"

From ST researcher: "E+A galaxies would be BOTH post-starburst galaxies and would be early-type galaxies"

From literature:
2020AAS...23525802G
2016hst..prop14785V 
2009MNRAS.397.1954F

**Comment by katieefrey** [comment]
change implemented!  (see also #332)
