### ISSUE TITLE
New Concepts: Near-Sun comets

### ISSUE THREAD

**Issue by mkelley** [astrothesaurus/UAT#337]
**Name the new concept**
Near-sun comets
Near-sun comets | Sundivers
Near-sun comets | Sungrazers
Near-sun comets | Sungrazers | Kreutz group
Near-sun comets | Sunskirters
Near-sun comets | Sunskirters | Kracht group
Near-sun comets | Sunskirters | Marsden group
Near-sun comets | Sunskirters | Meyer group

**Describe the concept**
Near-sun comets are a dynamical class of comets that have perihelion distances near or intersecting the Sun.  The terms for specific groups (Kreutz, Kracht, and Marsden) have been in use for many years, but the terms sundiver, sungrazer, and sunskirter were not well defined until Jones et al. 2017 (DOI:10.1007/s11214-017-0446-5).

Following Jones et al.:

Near-sun comets - all comets with perihelion distances within the perihelion distance of Mercury (66.1 solar radii).
Sunskirters - comets with perihelion distances within 1/2 the perihelion distance of Mercury (33.1 solar radii).
Sungrazers - comets with perihelion distances within the fluid Roche limit of the Sun.
Sundivers - comets with perihelion distances within 1 solar radius, i.e., their orbits intersect with the surface of the Sun.

**Describe where the concept fits within the existing hierarchy**
Solar system astronomy | Solar system | Small solar system bodies | Comets

**Provide 1-3 supporting articles**
Jones et al. 2017 DOI:10.1007/s11214-017-0446-5
Sekanina and Chodas 2005 2005ApJS..161..551S
Lamy et al. 2013 2005ApJS..161..551S

**Please include any additional comments/feedback**
These concepts are based on my conversations with Matthew Knight (US Naval Academy, @mmk8a )

**Comment by katieefrey** [comment]
Others have also expressed an interest in updating and fleshing out the comet section, so I have added these concepts.  They give existing "Kreutz sungrazers" (now renamed "Kreutz group") more context, and are well defined by the Jones, et al. paper.
