### ISSUE TITLE
Modify Concepts: 221, 2045, 719

### ISSUE THREAD

**Issue by msdemlei** [astrothesaurus/UAT#338]
There are currently a few concepts with two definitions, which I think
the UAT shouldn't have.  Specifically:

http://astrothesaurus.org/uat/2045

Here, it would seem the double element is really used as a paragraph.
While I think the definition as a whole could be streamlined a bit so it
works better in a single paragraph, I'd say a stopgap measure is to just
join the two definitions.

http://astrothesaurus.org/uat/221

This one appears to be an editorial oversight, as the definitions seem
to come from two different sources and should just be merged, perhaps
to:

```
  A limiting mass of about 1.44 Solar masses that a non-rotating star
  can attain without collapsing.  Over this critical mass, the
  degeneracy pressure will be unable to bear the load of the bulk mass.
```

http://astrothesaurus.org/uat/719

This one is trouble, in that  "HD catalog" and "HD system" really should
not be in one concept.  I'd throw out the "HD system" meaning and
definition and schedule it for addition as a separate term if we really
think there's demand for it.

**Comment by katieefrey** [comment]
Definitions cleaned up.  Each of these had a new definition from the EDA, and an older definition from another source.  I've removed the secondary definition.  Examination of HD catalog vs HD system will have to wait for a larger release, I'll make another issue for that.
