### ISSUE TITLE
New Concept: Pulsar Wind Nebula / Plerion

### ISSUE THREAD

**Issue by cbrisboi** [astrothesaurus/UAT#341]
**Name the new concept**
Pulsar Wind Nebula
Plerion

**Describe the concept**
Pulsar Wind Nebulae refer to the region beyond the pulsar magnetosphere where the escaped particles flow relatively unimpeded before they reach a termination shock against the surrounding medium. Depending on the age of the pulsar generating the wind, this surrounding medium may be leftover from the supernova producing the pulsar (resulting in whats known as a filled supernova remnant, or as they were historically known, a plerion) , or the interstellar medium (such as Geminga).

Plerion is something I have encountered often enough in older texts that it might help to include both even though they are the same. 

**Describe where the concept fits within the existing hierarchy**
This is sufficiently distinct from pulsars since studies are specifically done on PWNe, rather than pulsars themselves. Although pulsars are the ultimate originator of energy driving the wind. But I think it makes sense to link this to pulsars and supernova remnants (possibly nebulae?)

**Provide 1-3 supporting articles**
There are certainly many more, this is merely a few,
https://iopscience.iop.org/article/10.1088/0004-637X/726/1/35
https://aip.scitation.org/doi/abs/10.1063/1.4772215
https://www.annualreviews.org/doi/10.1146/annurev.astro.44.051905.092528
https://www.aanda.org/articles/aa/full_html/2018/04/aa29377-16/aa29377-16.html

**Please include any additional comments/feedback**
This seems to be a simple gap in the UAT, rather than a "new concept in the literature"

**Comment by cbrisboi** [comment]
A better (clearer/concise) definition from Gaensler & Slane (2006) [https://doi.org/10.1146/annurev.astro.44.051905.092528 or link above]

> A bubble of shocked relativistic particles, produced when a pulsar’s relativistic wind interacts with its environment

This might be preferable to my verbose version, or some combination of the two may be better still.

**Comment by katieefrey** [comment]
Yes, this does seem to be a simple gap! This concept will likely be included in the upcoming release.

**proposed concept details**
Preferred label: Pulsar wind nebulae
Alt label: Plerion

location in hierarchy:
- ISM --> Nebulae --> Supernova remnants --> Pulsar wind nebulae
- ISM --> Nebulae --> Pulsar wind nebulae

Related concepts: Pulsars
Examples: Crab nebula
Definition: A bubble of shocked relativistic particles, produced when a pulsar’s relativistic wind interacts with its environment. Gaensler & Slane (2006) [https://doi.org/10.1146/annurev.astro.44.051905.092528]
