### ISSUE TITLE
Cosmology, Exoplanet, Galactic, and Interdisciplinary astronomy concepts often used in educational settings

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#347]
**Proposed new concepts and hierarchy locations**
_Cosmology_
Cosmological models > Geocentric model
Cosmological models > Heliocentric model
Cosmology > Cosmological principle

_Exoplanet astronomy_
Exoplanet systems > Exocomets
Natural satellites (Extrasolar) > Exomoons

_Galactic and extragalactic astronomy_
Barred spiral galaxies > Galactic bar

_Interdisciplinary astronomy_
Sociology of astronomy > Cultural astronomy
Sociology of astronomy > Indigenous astronomy

**Please include any additional comments/feedback**
Concepts proposed by Dr. Markus Nielbock, IAU Office of Astronomy for Education

**Comment by katieefrey** [comment]
Geocentric and Heliocentric models should have related concept Geocentric and Heliocentric orbits.

Exomoon is an altLabel for "Natural satellites (extrasolar)" but I agree that Exomoon is a much nicer, catchier concept label.

Is "Galactic bar" specific to our the Milky way or is this a more general concept for galaxy bars?

**Comment by rpoleski** [comment]
"Galactic bar" is a general concept.

**Comment by katieefrey** [comment]
It's proposed location in the hierarchy suggests a general concept was intended.  However, the use of the word "Galactic" paired with the singular form of the concept suggests it was intended to refer to a bar in the Milky Way specifically.

Keeping in line with the rest of the UAT, the best approach may be to add "Galaxy bars" under "Barred spiral galaxies" and then add "Galactic bar" as a child of "Milky Way Galaxy physics" so it can be a sibling of "Galactic bulge" and "Galactic center."

**Comment by astroamlopez** [comment]
Proposed new concepts and hierarchy locations

Interdisciplinary astronomy
(remove) Sociology  of astronomy
(remove) Archaeoastronomy
Cultural astronomy > Archaeoastronomy
Cultural astronomy > Ethnoastronomy

Concepts proposed by Dr. Alejandro López, astronomer and anthropologist, ethnoastronomer, chair of the IAU WG astronomical heritage in danger.

**Comment by astroamlopez** [comment]
This organization of concepts much better reflects the academic consensus since the mid-1990s. Cultural astronomy is thought of as the general umbrella that includes archaeoastronomy and ethnoastronomy as two main branches. This can be seen in the generalized uses in the ISAAC, the SEAC and the SIAC, the main international organizations on these subjects.
In the current thesaurus ethnoastronomy is subsumed under archaeoastronomy, which is not correct for the use of the terms for decades. Today ethnoastronomy refers to the socio-cultural approach to the astronomies of any contemporary human group, using the tools of ethnography, ethnology, anthropology and sociology.

**Comment by katieefrey** [comment]
@astroamlopez  Thank you for your feedback on this!  Here is what I have after considering what both you and Nielbock wrote and consulting with another astronomy historian.  How does this look?

Interdisciplinary astronomy > Cultural astronomy > Archaeoastronomy
Interdisciplinary astronomy > Cultural astronomy > Archaeoastronomy > Megalithic astronomy
Interdisciplinary astronomy > Cultural astronomy > Ethnoastronomy
Interdisciplinary astronomy > Cultural astronomy > Ethnoastronomy > Indigenous astronomy
Interdisciplinary astronomy > Cultural astronomy > Sociology of astronomy

**Comment by astroamlopez** [comment]
Hi Katie!!!

Thank you for the response! I wasn't sure if my comments had reached you.
I agree with most of the suggestions. I only disagree on the idea of separating a "sociology from astronomy". In the field of cultural astronomy, ethnoastronomy also encompasses what is called the sociology of astronomy. The separation anthropology-ethnology vs. Sociology obeys historical reasons linked to colonialist views that separated the exotic and wild world from the civilized one. That is why I think it is not good to reproduce them in the field of cultural astronomy. In this field, although some have proposed the division, there are no researchers who have really applied the term sociology of astronomy to what they do and several of us who do work of this style call it ethnoastronomy. If you are interested, I have papers discussing these topics, which I am attaching to this email.

On the other hand, as a further refinement, I would add:
Interdisciplinary astronomy > Cultural astronomy >Socio-cultural history of astronomy
Interdisciplinary astronomy > Cultural astronomy >Intercultural astronomy education
These last two cases collect the research initiatives in this sense that have been taking place for about 15 years.

A great pleasure to collaborate. Please keep me posted on the discussion.

Regards!

Alejandro López

________________________________
De: Katie Frey ***@***.***>
Enviado: viernes, 24 de junio de 2022 14:22
Para: astrothesaurus/UAT ***@***.***>
Cc: astroamlopez ***@***.***>; Mention ***@***.***>
Asunto: Re: [astrothesaurus/UAT] Cosmology, Exoplanet, Galactic, and Interdisciplinary astronomy concepts often used in educational settings (Issue #347)


@astroamlopez<https://github.com/astroamlopez> Thank you for your feedback on this! Here is what I have after considering what both you and Nielbock wrote and consulting with another astronomy historian. How does this look?

Interdisciplinary astronomy > Cultural astronomy > Archaeoastronomy
Interdisciplinary astronomy > Cultural astronomy > Archaeoastronomy > Megalithic astronomy
Interdisciplinary astronomy > Cultural astronomy > Ethnoastronomy
Interdisciplinary astronomy > Cultural astronomy > Ethnoastronomy > Indigenous astronomy
Interdisciplinary astronomy > Cultural astronomy > Sociology of astronomy

**Comment by katieefrey** [comment]
@astroamlopez 

Dear Alejandro,

I appreciate you thinking deeply on this issue.  To rephrase what you wrote in order to help make sure I understand properly, are you essentially saying that studies of astronomers in a Western/"civilized" context are called "sociology," while studies of astronomers in non-Western/"exotic" contexts are called "ethnoastronomy"?  I have not had seen it that way before, and I do agree it is troubling.

Also, I did not receive the attachments that you mentioned, but I am interested in reading them.  Could you email them to me directly, rather than replying to this github issue?   kfrey@cfa.harvard.edu

Thank you!
Katie

**Comment by katieefrey** [comment]
_Added/Modified_
Cosmological models > Geocentric model
Cosmological models > Heliocentric model
Cosmology > Cosmological principle
Exoplanet systems > Exocomets
Barred spiral galaxies > Galaxy bars
Milky Way Galaxy physics > Galactic bar
Cultural astronomy > Archaeoastronomy
Cultural astronomy > Ethnoastronomy > Indigenous astronomy
Cultural astronomy > Sociology of astronomy [see note below]

_Not Added_
Natural satellites (Extrasolar) > Exomoons

Exomoons is already considered with synonymous with "Natural satellites (Extrasolar). It is included as a non-preferred label for the concept, so it can be used in lieu of "Natural satellites (Extrasolar)" as long as the concept URI (http://astrothesaurus.org/uat/483) or identifier (483) is included to make the connection clear.

_Pending further discussion_ 
deprecation of "Sociology of astronomy" and merger into "Ethnoastronomy," see #357

@astroamlopez
The UAT 5.0 release is scheduled for tomorrow, and I wont be able to address this topic in time since deprecating (removing) a concept is something I need to handle with care.  I decided to close this issue as the other suggestions listed above have been acted on.  However I am continuing the discussion in a new issue (#357).
