### ISSUE TITLE
New Concept: Data Sonification

### ISSUE THREAD

**Issue by jradavenport** [astrothesaurus/UAT#353]
**Name the new concept**
Data Sonification

**Describe the concept**
Data sonification - representing data as sound - is increasingly common in astronomy and public outreach activities. This is conceptually related to visualization, but is a distinct branch of data representation and useful for data exploration. 

**Describe where the concept fits within the existing hierarchy**
Interdisciplinary Astronomy / Computation Astronomy / Astronomy Data Analysis

**Provide 1-3 supporting articles**
- https://ui.adsabs.harvard.edu/abs/2012JSARA...6...21T/abstract
- https://ui.adsabs.harvard.edu/abs/2022NatAs...6...22H/abstract
- https://ui.adsabs.harvard.edu/abs/2022arXiv220512984G/abstract

**Please include any additional comments/feedback**

**Comment by jradavenport** [comment]
cc: @dhuppenkothen @pampin

**Comment by katieefrey** [comment]
Concepts to help identify areas of accessible astronomy are very relevant, thanks for pointing this out.  I've added it for the upcoming 5.0.0 release.
