### ISSUE TITLE
Modify Concept: "Ethnoastronomy" and "Sociology of Astronomy"

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#357]
continuing the conversation from #347 , which was closed as the majority items were addressed in UAT v5.0

Proposal summary:
1) deprecate "Sociology of astronomy" and merge into "Ethnoastronomy"
2) add:
Interdisciplinary astronomy > Cultural astronomy >Socio-cultural history of astronomy
Interdisciplinary astronomy > Cultural astronomy >Intercultural astronomy education

"Essentially what I am pointing out is that, on the one hand, from my point of view the interdisciplinary study of the astronomies of contemporary groups (Western or non-Western) should be called ethnoastronomy and is usually designated as such. On the other hand, when a few authors distinguish between socio-astronomy and ethno-astronomy, that distinction ultimately refers to the historical disciplinary distinction between sociology and anthropology. By following this separation, it is assumed that the astronomies of Western societies must be studied differently from the others (analogous to the way in which sociology was supposed to study Western society and anthropology the "others"). But that distinction (beyond the fact that for reasons of academic policy both disciplines are formally separated) was profoundly revised after the decolonial turn after the Second World War. Thanks to this, today it is considered that it is possible to approach socio-anthropologically the study of any human society. That is why it makes no sense to me to introduce in cultural astronomy a separation between socio and ethno astronomy, when in fact it is not a separation that is really used. In conclusion I would only talk about ethnoastronomy."
-- email from Dr. Alejandro López, astronomer and anthropologist, ethnoastronomer, chair of the IAU WG astronomical heritage in danger.

**Comment by BartlettAstro** [comment]
@ebortey Could you please split this issue into the suggested merge plus a separate issue for each of the proposed new concepts? The suggested merge should go into milestone "Release 5.1.10" while the other two should be milestone "Next UAT Release."

**Comment by BartlettAstro** [comment]
Split into 3 issues to address separately on their individual merits.
Issue #434 Deprecate Concept: "Sociology of astronomy"
Issue #435 [New Concept]: Socio-cultural history of astronomy
Issue #436  [New Concept]: Intercultural astronomy education

**Comment by danielchivvis** [comment]
Deprecated Concept "Sociology of astronomy". Added "Astrosociology" and "Sociology of astronomy" as Alternative labels to "Ethnoastronomy"
