### ISSUE TITLE
Modify Concept: Hickson compact group

### ISSUE THREAD

**Issue by SebastienDerriere** [astrothesaurus/UAT#363]
[Hickson compact group](http://astrothesaurus.org/uat/729) has currently **group** in singular form.

It should be renamed to "Hickson compact group**s**" (plural for groups).

It makes sense to have the sigular form for "group" when there is a single group with multiple members, like "Amor group" or "Centaur group".
But for Hickson compact groups, there are [multiple groups](https://astronomy.swin.edu.au/cosmos/h/Hickson+Compact+Groups), each with their own galaxy members.
It would be better to use the plural for groups, like it is the case for [Galaxy groups](http://astrothesaurus.org/uat/597).

**Comment by BartlettAstro** [comment]
@ebortey Could you please find an authoritative defintion?

**Comment by BartlettAstro** [comment]
Definition from An Etymological Dictionary of Astronomy and Astrophysics

A list of 100 compact groups of galaxies that were identified by a systematic search of the Palomar Observatory Sky Survey red prints. Each group contains four or more galaxies, has an estimated mean surface brightness brighter than 26.0 magnitude per arcsec2 and satisfies an isolation criterion.

Hickson, Paul, 1982, ApJ 255, 382

**Comment by danielchivvis** [comment]
Added definition.
