### ISSUE TITLE
Modify Concept: VY Sculpturis stars

### ISSUE THREAD

**Issue by SebastienDerriere** [astrothesaurus/UAT#367]
**VY Sculpturis stars**
http://astrothesaurus.org/uat/1782

**Describe the change**
Concept should be renamed to **VY Sculptoris stars**
See genetive for Sculptor constellation [in IAU list](https://www.iau.org/public/themes/constellations/).

ADS search for "VY Sculpturis" returns [only 1](https://ui.adsabs.harvard.edu/search/p_=0&q=%22VY%20Sculpturis%22&sort=date%20desc%2C%20bibcode%20desc) result, [versus 162](https://ui.adsabs.harvard.edu/search/p_=0&q=%22VY%20Sculptoris%22&sort=date%20desc%2C%20bibcode%20desc) for "VY Sculptoris".

**Comment by danielchivvis** [comment]
Revised Preferred Label. Added VY Sculpturis stars as Alternative Label.
