### ISSUE TITLE
Add Branch: Calibration, submitted by Sarah Weissman (STScI) 5/17/2016

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#37]
I am still working with the developers of the Astronomer's Proposal Tool (APT) at STScI, who are planning on using the UAT to replace their existing target vocabulary. I am pretty sure that many of the terms they currently use for describing calibration "targets" are not in the thesaurus. I was thinking that they could go under

Observational Astronomy -> Techniques -> Calibration

**Comment by katieefrey** [comment]
Placeholder to remind me to get more input from Sarah.

**Comment by seweissman** [comment]
Here is the working list for APT.  For the UAT, some of these probably need a noun following them, like "astrometric calibration" (or "astrometric standard stars") vs. "astrometric." The last 8 were added after I last looked at the list, and I can only assume these are intended to be standard target types. I think this list probably needs a scientist familiar with instrument calibration to look at it.

Aperture location
Astrometric
Coronagraphic
Detector linearity test
External flat field
Focus test
Line spread function
Persistence test
Photometric
Point spread function
Pointing and jitter test
Spectrophotometric
Stray light test
Target acquisition test
Telescope/sky background
Wavelength

A stars
Binary stars
Emission nebulae
Emission line stars
G stars
Open star clusters
Planetary nebulae
White dwarfs

**Comment by katieefrey** [comment]
@seweissman @stlibrary18 

This issue has been outstanding for a while now, I've just not been sure how to add it.  I know we're coming down to the wire, but if these are still wanted/needed, I'd like to get something in for the next release.

At the very least, maybe just add in the "Calibration" concept?
Observational Astronomy -> Techniques -> Calibration

**Existing possibly related concepts:**
Obs. astronomy -> Techniques -> Astrometry -> Standard stars
Obs. astronomy -> Techniques -> Astrometry -> Standard stars -> Comparison stars
Obs. astronomy -> Techniques -> Astrometry -> Standard stars -> Photometric standard stars
Obs. astronomy -> Techniques -> Astrometry -> Stellar distance -> Standard candles

**Comment by BartlettAstro** [comment]
At this point, we have

Observational Astronomy --> Astronomical Techniques --> Calibration
Observational Astronomy --> Astronomical Techniques --> Calibration --> Flux Calibration

Stellar astronomy --> Stellar types --> Early-type stars --> A stars
Stellar astronomy --> Stellar types --> Stellar spectral types --> A stars 
Stellar astronomy --> Stellar types --> Early-type stars --> A stars --> Ae stars --> Herbig Ae/Be stars
Stellar astronomy --> Stellar types --> Early-type stars --> A stars --> A dwarf stars
Stellar astronomy --> Stellar types --> Early-type stars --> A stars --> Am stars 
Stellar astronomy --> Stellar types --> Early-type stars --> A stars --> A giant stars
Stellar astronomy --> Stellar types --> Early-type stars --> A stars --> Ap stars --> ...
Stellar astronomy --> Stellar types --> Early-type stars --> A stars --> A subdwarf stars
Stellar astronomy --> Stellar types --> Early-type stars --> A stars --> A subgiant stars
Stellar astronomy --> Stellar types --> Early-type stars --> A stars --> A supergiant stars

Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Relativistic binary stars 
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Spectroscopic binary stars
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Visual binary stars
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Wide binary stars
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Close binary stars --> ...
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Companion stars --> ...
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Detached binary stars
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Eclipsing binary stars --> ...
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Astrometric binary stars 
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Interferometric binary stars
Stellar astronomy --> Stellar types --> Multiple stars --> Binary stars --> Double periodic variable stars

Interstellar medium --> Nebulae --> Emission nebulae
Interstellar medium --> Nebulae --> Emission nebulae --> Planetary nebulae --> Planetary nebulae nuclei
Interstellar medium --> Nebulae --> Emission nebulae --> H II regions --> ...

Stellar astronomy --> Stellar types --> Emission line stars
Stellar astronomy --> Stellar types --> Emission line stars --> Me stars --> Me variable stars
Stellar astronomy --> Stellar types --> Emission line stars --> Mira variable stars
Stellar astronomy --> Stellar types --> Emission line stars --> S Doradus stars
Stellar astronomy --> Stellar types --> Emission line stars --> Symbiotic binary stars --> ...
Stellar astronomy --> Stellar types --> Emission line stars --> T Tauri stars --> ...
Stellar astronomy --> Stellar types --> Emission line stars --> X-ray stars --> Single x-ray stars
Stellar astronomy --> Stellar types --> Emission line stars --> Z Andromedae stars
Stellar astronomy --> Stellar types --> Emission line stars --> Early-type emission stars --> ...
Stellar astronomy --> Stellar types --> Emission line stars --> Flash stars
Stellar astronomy --> Stellar types --> Emission line stars --> FU Orionis stars
Stellar astronomy --> Stellar types --> Emission line stars --> Gamma Cassiopeiae stars
Stellar astronomy --> Stellar types --> Emission line stars --> H-alpha stars
Stellar astronomy --> Stellar types --> Emission line stars --> Luminous blue variable stars --> S Doradus stars
Stellar astronomy --> Stellar types --> Emission line stars --> Be stars --> ...

Stellar astronomy --> Stellar types --> Intermediate-type stars --> G stars
Stellar astronomy --> Stellar types --> Stellar spectral types --> G stars
Stellar astronomy --> Stellar types --> Intermediate-type stars --> G stars --> G dwarf stars
Stellar astronomy --> Stellar types --> Intermediate-type stars --> G stars --> G giant stars
Stellar astronomy --> Stellar types --> Intermediate-type stars --> G stars --> G subdwarf stars
Stellar astronomy --> Stellar types --> Intermediate-type stars --> G stars --> G subgiant stars
Stellar astronomy --> Stellar types --> Intermediate-type stars --> G stars --> G supergiant stars

Stellar astronomy --> Star clusters --> Open star clusters
Stellar astronomy --> Star clusters --> Open star clusters --> O clusters
Stellar astronomy --> Star clusters --> Open star clusters --> Young star clusters

Interstellar medium --> Nebulae --> Emission nebulae --> Planetary nebulae
Interstellar medium --> Nebulae --> Emission nebulae --> Planetary nebulae --> Planetary nebulae nuclei

Stellar astronomy --> Stellar types --> Stellar evolutionary types --> White dwarf stars
Stellar astronomy --> Stellar remnants --> Compact objects --> White dwarf stars
Stellar astronomy --> Stellar types --> Stellar evolutionary types --> White dwarf stars --> DC stars
Stellar astronomy --> Stellar types --> Stellar evolutionary types --> White dwarf stars --> ZZ Ceti stars
Stellar astronomy --> Stellar types --> Stellar evolutionary types --> White dwarf stars --> DZ stars
Stellar astronomy --> Stellar types --> Stellar evolutionary types --> White dwarf stars --> DQ stars
Stellar astronomy --> Stellar types --> Stellar evolutionary types --> White dwarf stars --> DA stars
Stellar astronomy --> Stellar types --> Stellar evolutionary types --> White dwarf stars --> DB stars
Stellar astronomy --> Stellar types --> Stellar evolutionary types --> White dwarf stars --> DO stars --> PG 1159 stars

**Comment by BartlettAstro** [comment]
Issue #396 
Aperture location

Issue #397 
Astrometric calibration

Issue #398
Coronagraphic calibration

Issue #399
Detector linearity test 

Issue #400
External flat field

Issue #401
Focus test

Issue #402
Line spread function

Issue #403
Persistence test

Issue #404
Photometric calibration

Issue #405
Point spread function

Issue #406
Pointing and jitter test

Issue #407
Spectrophotometric calibration

Issue #408
Stray light test

Issue #409
Target acquisition test

Issue #410
Telescope/sky background

Issue #411
Wavelength calibration

**Comment by BartlettAstro** [comment]
All concepts suggested here have been addressed in release 5.0.0 (or earlier) or have moved to their own issue.
