### ISSUE TITLE
Revise concepts under "Stellar abundances"

### ISSUE THREAD

**Issue by gorbynet** [astrothesaurus/UAT#39]
Suggest revising the terms under 'Stellar abundances'. At present, they are 

- Beryllium
- Boron
- Helium
- Lithium

These are chemical elements, not types of abundance, and therefore don't meet any of the three BT/NT relationships:

- All-and-some
- Whole/part
- Class/instance

I suggest revising the terms to:

- Beryllium abundance
- Boron abundance
- Helium abundance
- Lithium abundance
i.e. making four new terms, with the relevant chemical elements linked as reltaed terms.

**Comment by katieefrey** [comment]
Excellent point, thank you!  I'll close this issue once I have a chance to update the thesaurus.

**Comment by katieefrey** [comment]
Concepts updated.
