### ISSUE TITLE
Modify Concept: Radar astronomy

### ISSUE THREAD

**Issue by ebortey** [astrothesaurus/UAT#415]
**Name the concept in question**
Radar astronomy
http://astrothesaurus.org/uat/1329

**Describe the change**
In Issue #76 
@katieefrey recommended that we add definition or scope note for the different types of astronomy (infrared, radio, ultraviolet, etc) under Observational astronomy > Methods.

originally submitted by François Ochsenbein (CDS)

@katieefrey found these definitions from Hubblesite.org
http://hubblesite.org/reference_desk/faq/answer.php.id=70&cat=light
Radio waves are longer than 1 mm

**Please include any additional comments/feedback**
This issue has been created to track the modification of radar astronomy

**Comment by BartlettAstro** [comment]
@danielchivvis I think this is ready for Pool Party.

**Comment by danielchivvis** [comment]
Added new definition.
