### ISSUE TITLE
Modify Concept: Ultraviolet astronomy

### ISSUE THREAD

**Issue by ebortey** [astrothesaurus/UAT#417]
**Name the concept in question**
Ultraviolet astronomy
http://astrothesaurus.org/uat/1736

**Describe the change**
In Issue #76 
@katieefrey recommended that we add definition or scope note for the different types of astronomy (infrared, radio, ultraviolet, etc) under Observational astronomy > Methods.

originally submitted by François Ochsenbein (CDS)

@katieefrey found these definitions from Hubblesite.org
http://hubblesite.org/reference_desk/faq/answer.php.id=70&cat=light
Ultraviolet radiation has wavelengths of 10 – 310 nm

**Please include any additional comments/feedback**
This issue has been created to track the modification of Ultraviolet astronomy

**Comment by ebortey** [comment]
The current for this topic is:
The study of astronomical objects in the ultraviolet portions of the electromagnetic spectrum, in the waveband 3000 Å to about 10 Å. At these wavelengths, the atmosphere prevents ultraviolet radiation from reaching the Earth surface. Therefore ground-based observatories cannot observe in the ultraviolet. Only with the advent of space-based telescopes has this area of astronomy become available for research.
 	- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

I propose that the definition should be:
Ultraviolet astronomy is "the study of astronomical objects in the ultraviolet portions of the electromagnetic spectrum, in the waveband 3000 Å to about 10 Å. At these wavelengths, the atmosphere prevents ultraviolet radiation from reaching the Earth surface. Therefore ground-based observatories cannot observe in the ultraviolet. Only with the advent of space-based telescopes has this area of astronomy become available for research."
 	- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

Ultraviolet is "the part of the electromagnetic radiation beyond the violet end of the visible spectrum with wavelenghts approximately in the range 50 Å to 4,000 Å."
 	- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

**Comment by BartlettAstro** [comment]
@danielchivvis @ebortey I think we can use one definition here because in this case the definition of UV astronomy includes the range of wavelengths.

**Comment by danielchivvis** [comment]
Consider revisiting in the future if more specific range for UV wavelength is needed.
