### ISSUE TITLE
Modify Concept: Optical astronomy

### ISSUE THREAD

**Issue by ebortey** [astrothesaurus/UAT#418]
**Name the concept in question**
Optical astronomy
http://astrothesaurus.org/uat/1776

**Describe the change**
In Issue #76 
@katieefrey recommended that we add definition or scope note for the different types of astronomy (infrared, radio, ultraviolet, etc) under Observational astronomy > Methods.

originally submitted by François Ochsenbein (CDS)

@katieefrey found these definitions from Hubblesite.org
http://hubblesite.org/reference_desk/faq/answer.php.id=70&cat=light
Visible light covers the range of wavelengths from 400 – 700 nm

**Please include any additional comments/feedback**
This issue has been created to track the modification of optical astronomy

**Comment by ebortey** [comment]
The current definition for optical astronomy comes from Wikipedia, an often unreliable source. Additionally it doesn't contain the wavelength range for visible light.

I propose that the definition be:
"Optical astronomy refers to an area of astronomy where astronomers observe and analyse light from the Universe that falls within the wavelength range that the human eye is sensitive to, also referred to as visible light."

- ESA

Visible light is "the portion of the electromagnetic radiation that can be seen by the human eye. the wavelengths extend from about 400 nm (violet) to 750 nm (red)."

- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malay

**Comment by BartlettAstro** [comment]
@danielchivvis I think this is ready for PoolPary

**Comment by katieefrey** [comment]
Similar to #414 and #416, one of these two definitions isn't for this specific concept.  The second is relevant information, but "Visible light is "the portion of the electromagnetic radiation that can be seen by the human eye. the wavelengths extend from about 400 nm (violet) to 750 nm (red)."" is not the definition of optical astronomy.

Instead, I think combing them together into one definition makes more sense. 

An area of astronomy where astronomers observe and analyse light from the Universe that falls within the wavelength range that the human eye is sensitive to, about 400 nm (violet) to 750 nm (red), which is also referred to as visible light.

Combined and modified from ESA and An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malay

I did take more liberties here to take out some of the repeated language as well.

**Comment by danielchivvis** [comment]
Added combined definition.
