### ISSUE TITLE
Modify Concept: Gamma-ray astronomy

### ISSUE THREAD

**Issue by ebortey** [astrothesaurus/UAT#420]
**Name the concept in question**
Gamma-ray astronomy
http://astrothesaurus.org/uat/628

**Describe the change**
In Issue #76 
@katieefrey recommended that we add definition or scope note for the different types of astronomy (infrared, radio, ultraviolet, etc) under Observational astronomy > Methods.

originally submitted by François Ochsenbein (CDS)

@katieefrey found these definitions from Hubblesite.org
http://hubblesite.org/reference_desk/faq/answer.php.id=70&cat=light
Gamma rays have the shortest wavelengths, < 0.01 nanometers

**Please include any additional comments/feedback**
This issue has been created to track the modification of gamma-ray astronomy

**Comment by ebortey** [comment]
The current definition for this topic is:
The study of gamma rays from extraterrestrial sources, especially gamma-ray bursts.
 	- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

This does not explain what gamma rays are, so I propose the definition to be:
Gamma-ray astronomy is "the study of gamma rays from extraterrestrial sources, especially gamma-ray bursts."
 	- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

Gamma-rays are "an electromagnetic wave with a typical wavelength less than 10<sup>-2</sup> (10 Å <sup>-12</sup> m), corresponding to frequencies above 10<sup>19</sup> Hz and photon energies above 100 keV."
 	- An Etymological Dictionary of Astronomy and Astrophysics, by M. Heydari-Malayeri

**Comment by BartlettAstro** [comment]
@danielchivvis I think this is ready for PoolParty.

**Comment by danielchivvis** [comment]
Added combined definition.
