### ISSUE TITLE
Clean up of sibling/ancestor pairs, submitted by Sarah Weissman (STScI) 8/11/2016 

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#5]
I also have a large-ish list of pairs of concepts that are both siblings and ancestors, e.g.:
   Galactic and extragalactic astronomy,Galaxy physics,Galaxy dynamics,,,,,,,
   Galactic and extragalactic astronomy,Galaxy physics,Galaxy processes,Galaxy dynamics,,,,,,
I will attach the list but maybe we should start a Google doc somewhere and we can make it a group effort to fix these as we have time? Some of them are obvious how to fix, but not all. Just a thought. I'll let you decide!

See attached
[sibling-ancestor-pairs.txt](https://github.com/katieefrey/UAT/files/564427/sibling-ancestor-pairs.txt)

**Comment by katieefrey** [comment]
For the suggestions:

Galactic and extragalactic astronomy-->Galaxy clusters-->Rich clusters
Galactic and extragalactic astronomy-->Galaxy clusters-->Poor clusters
Galactic and extragalactic astronomy-->Galaxy clusters-->High-redshift clusters

Do these concepts mean something out of the context of the hierarchy? To avoid potential confusion with star clusters, I propose "Rich galaxy clusters," "Poor galaxy clusters," and "High-redshift galaxy clusters."

**Comment by katieefrey** [comment]
Cosmology->Astronomical radiation sources
-> Gamma-ray sources
-> Visible sources

For clarity I propose "Gamma-ray radiation sources," "visible radiation sources," etc, and to update the existing concepts to be similar.

**Comment by katieefrey** [comment]
"And I just noticed that we used "O giant stars" instead of "O giants" like the rest of the "? giants" labels. These should probably be consistent."

I agree these should be consistent.  I favor "O giant stars," "A giant stars," "B giant stars," etc to give the concepts more intrinsic context. Thoughts?

**Comment by katieefrey** [comment]
In cases where a concept is its direct aunt/uncle, I could see how they could be "fixed," but I hesitate to remove cases where the nesting goes deeper than that.  Part of the point of the UAT is for concepts to exist in a poly hierarchy, for them to be found through multiple paths.  I'm not sure we really need to clean up all the instances listed below.

I have used strikethrough to indicate the concept paths which have been eliminated via other updates to the UAT, and some comments in bold.  Not a comprehensive assessment.

==========

Galactic and extragalactic astronomy,Galaxy physics,Galaxy dynamics,,,,,,,
Galactic and extragalactic astronomy,Galaxy physics,Galaxy processes,Galaxy dynamics,,,,,,

~~Stellar astronomy,Stellar types,Evolved stars,Giant stars,S stars,,,,,~~
Stellar astronomy,Stellar types,Evolved stars,Giant stars,Late-type giants,Heavy metal stars,S stars,,,

Galactic and extragalactic astronomy,Galaxies,Quasar-galaxy pairs,,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Active galactic nuclei,Quasars,Quasar-galaxy pairs,,,,

Galactic and extragalactic astronomy,Galaxies,Radio jets,,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Active galactic nuclei,Radio jets,,,,,

Galactic and extragalactic astronomy,Galaxies,Starburst galaxies,,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Starburst galaxies,,,,,,

Solar system astronomy,Solar system,Oort cloud,,,,,,,
Solar system astronomy,Solar system,Small solar system bodies,Comets,Long period comets,Oort cloud,,,,

Solar system astronomy,Solar system,The Moon,,,,,,,
Solar system astronomy,Solar system,Natural satellites,The Moon,,,,,,

~~Solar system astronomy,Solar system,Meteors,,,,,,,~~
Solar system astronomy,Solar system,Meteoroids,Meteors,,,,,,

Solar system astronomy,Planetary science,Planetary atmospheres,Atmospheric tides,,,,,,
Solar system astronomy,Planetary science,Planetary atmospheres,Earth atmosphere,Atmospheric tides,,,,,

Solar system astronomy,Planetary science,Planetary atmospheres,Stratopause,,,,,,
Solar system astronomy,Planetary science,Planetary atmospheres,Earth atmosphere,Stratopause,,,,,

Solar system astronomy,Planetary science,Planetary atmospheres,Water vapor,,,,,,
Solar system astronomy,Planetary science,Planetary atmospheres,Earth atmosphere,Greenhouse gases,Water vapor,,,,

Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Beta Cephei stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Multi-periodic variable stars,Beta Cephei stars,,,

Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Double-mode variable stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Multi-periodic variable stars,Double-mode variable stars,,,

Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Delta Scuti variable stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Multi-periodic variable stars,Delta Scuti variable stars,,,

**S Vulpeculae stars deprecated on September 13, 2018 12:39 PM**
~~Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,S Vulpeculae stars,,,,~~
~~Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Long period variable stars,S Vulpeculae stars,,,~~

Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Mira variable stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Long period variable stars,Mira variable stars,,,

Stellar astronomy,Stellar types,Novae,,,,,,,
Stellar astronomy,Stellar types,Multiple stars,Binary stars,Close binary stars,Interacting binary stars,Semi-detached binary stars,Cataclysmic variable stars,Novae,,

Stellar astronomy,Stellar types,Novae,,,,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Cataclysmic variable stars,Novae,,,,

Stellar astronomy,Stellar remnants,Compact objects,Black holes,,,,,,
~~Stellar astronomy,Stellar remnants,Compact objects,Compact binary systems,Compact binary components,Black holes,,,,~~
(Maybe compact binary systems should be a sibling to Compact objects since a system is multiple objects,  not an object?)

Stellar astronomy,Stellar remnants,Compact objects,Neutron stars,,,,,,
~~Stellar astronomy,Stellar remnants,Compact objects,Compact binary systems,Compact binary components,Neutron stars,,,,~~

Astrophysical processes,Nuclear astrophysics,Nucleosynthesis,Helium burning,,,,,,
Astrophysical processes,Nuclear astrophysics,Nucleosynthesis,Stellar nucleosynthesis,Helium burning,,,,,

Astrophysical processes,Nuclear astrophysics,Nucleosynthesis,Hydrogen burning,,,,,,
Astrophysical processes,Nuclear astrophysics,Nucleosynthesis,Stellar nucleosynthesis,Hydrogen burning,,,,,

Observational astronomy,Techniques,Astrometry,Two-color diagrams,,,,,,
Observational astronomy,Techniques,Astrometry,Magnitude,Apparent magnitude,Two-color diagrams,,,,

Solar astronomy,Sunspots,,,,,,,,
Solar astronomy,Solar activity,Sunspots,,,,,,,

Solar astronomy,Solar flares,,,,,,,,
Solar astronomy,Solar activity,Solar flares,,,,,,,

Cosmology,Origin of the universe,Big Bang theory,,,,,,,
Cosmology,Big Bang theory,,,,,,,,

Interstellar medium,Supernova remnants,,,,,,,,
Interstellar medium,Nebulae,Supernova remnants,,,,,,,

Stellar astronomy,Stellar types,Emission line stars,Z Andromedae stars,,,,,,
Stellar astronomy,Stellar types,Emission line stars,Symbiotic binary stars,Z Andromedae stars,,,,,

Galactic and extragalactic astronomy,Galaxy physics,Galaxy structure,Radio cores,,,,,,
~~Galactic and extragalactic astronomy,Galaxy physics,Galaxy structure,Galaxy components,Galaxy nuclei,Active galactic nuclei,Radio cores,,,~~

**Gamma ray observatories might be on the ground**
Observational astronomy,Instrumentation,Observatories,Gamma-ray observatories,,,,,,
Observational astronomy,Instrumentation,Observatories,Space observatories,Gamma-ray observatories,,,,,

Stellar astronomy,Stellar remnants,Compact objects,Compact binary systems,Cataclysmic variable stars,SX Arietis variables,,,,
Stellar astronomy,Stellar remnants,Compact objects,Compact binary systems,Cataclysmic variable stars,Novae,Dwarf novae,SX Arietis variables,,

~~Stellar astronomy,Stellar remnants,Compact objects,Compact binary systems,Cataclysmic variable stars,Symbiotic novae,,,,~~
Stellar astronomy,Stellar remnants,Compact objects,Compact binary systems,Cataclysmic variable stars,Novae,Symbiotic novae,,,

Galactic and extragalactic astronomy,Galaxies,Active galaxies,Blazars,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Active galactic nuclei,Blazars,,,,,

~~Observational astronomy,Instrumentation,Siderostats,,,,,,,~~
Observational astronomy,Instrumentation,Stellar tracking devices,Siderostats,,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Am stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Magnetic stars,Magnetic variable stars,Am stars,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Strontium stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Heavy metal stars,Strontium stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Technetium stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Heavy metal stars,Technetium stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Manganese stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Ap stars,Manganese stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Manganese stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Heavy metal stars,Manganese stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Bp stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Magnetic stars,Bp stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Mercury-manganese stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Magnetic stars,Mercury-manganese stars,,,,,

~~Solar system astronomy,Solar system,Meteoroids,Meteorites,Bediasites,,,,,~~
Solar system astronomy,Solar system,Meteoroids,Meteorites,Tektites,Bediasites,,,,

~~Solar system astronomy,Solar system,Meteoroids,Meteorites,Moldavites,,,,,~~
Solar system astronomy,Solar system,Meteoroids,Meteorites,Tektites,Moldavites,,,,

**Comment by katieefrey** [comment]
In cases where a concept is its direct aunt/uncle, I could see how they could be "fixed," but I hesitate to remove cases where the nesting goes deeper than that.  Part of the point of the UAT is for concepts to exist in a poly hierarchy, for them to be found through multiple paths.  I'm not sure we really need to clean up all the instances listed below.

I have used strikethrough to indicate the concept paths which have been eliminated via other updates to the UAT, and some comments in bold.  Not a comprehensive assessment.

==========

Galactic and extragalactic astronomy,Galaxy physics,Galaxy dynamics,,,,,,,
Galactic and extragalactic astronomy,Galaxy physics,Galaxy processes,Galaxy dynamics,,,,,,

Galactic and extragalactic astronomy,Galaxies,Quasar-galaxy pairs,,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Active galactic nuclei,Quasars,Quasar-galaxy pairs,,,,

Galactic and extragalactic astronomy,Galaxies,Radio jets,,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Active galactic nuclei,Radio jets,,,,,

Galactic and extragalactic astronomy,Galaxies,Starburst galaxies,,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Starburst galaxies,,,,,,

Solar system astronomy,Solar system,Oort cloud,,,,,,,
Solar system astronomy,Solar system,Small solar system bodies,Comets,Long period comets,Oort cloud,,,,

Solar system astronomy,Solar system,The Moon,,,,,,,
Solar system astronomy,Solar system,Natural satellites,The Moon,,,,,,

Solar system astronomy,Planetary science,Planetary atmospheres,Atmospheric tides,,,,,,
Solar system astronomy,Planetary science,Planetary atmospheres,Earth atmosphere,Atmospheric tides,,,,,

Solar system astronomy,Planetary science,Planetary atmospheres,Stratopause,,,,,,
Solar system astronomy,Planetary science,Planetary atmospheres,Earth atmosphere,Stratopause,,,,,

Solar system astronomy,Planetary science,Planetary atmospheres,Water vapor,,,,,,
Solar system astronomy,Planetary science,Planetary atmospheres,Earth atmosphere,Greenhouse gases,Water vapor,,,,

Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Beta Cephei stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Multi-periodic variable stars,Beta Cephei stars,,,

Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Double-mode variable stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Multi-periodic variable stars,Double-mode variable stars,,,

Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Delta Scuti variable stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Multi-periodic variable stars,Delta Scuti variable stars,,,

Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Mira variable stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Long period variable stars,Mira variable stars,,,

Stellar astronomy,Stellar types,Novae,,,,,,,
Stellar astronomy,Stellar types,Multiple stars,Binary stars,Close binary stars,Interacting binary stars,Semi-detached binary stars,Cataclysmic variable stars,Novae,,

Stellar astronomy,Stellar types,Novae,,,,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Cataclysmic variable stars,Novae,,,,

Astrophysical processes,Nuclear astrophysics,Nucleosynthesis,Helium burning,,,,,,
Astrophysical processes,Nuclear astrophysics,Nucleosynthesis,Stellar nucleosynthesis,Helium burning,,,,,

Astrophysical processes,Nuclear astrophysics,Nucleosynthesis,Hydrogen burning,,,,,,
Astrophysical processes,Nuclear astrophysics,Nucleosynthesis,Stellar nucleosynthesis,Hydrogen burning,,,,,

Observational astronomy,Techniques,Astrometry,Two-color diagrams,,,,,,
Observational astronomy,Techniques,Astrometry,Magnitude,Apparent magnitude,Two-color diagrams,,,,

Solar astronomy,Sunspots,,,,,,,,
~~Solar astronomy,Solar activity,Sunspots,,,,,,,~~

~~Solar astronomy,Solar flares,,,,,,,,~~
Solar astronomy,Solar activity,Solar flares,,,,,,,

Cosmology,Origin of the universe,Big Bang theory,,,,,,,
~~Cosmology,Big Bang theory,,,,,,,,~~

Interstellar medium,Supernova remnants,,,,,,,,
Interstellar medium,Nebulae,Supernova remnants,,,,,,,

Stellar astronomy,Stellar types,Emission line stars,Z Andromedae stars,,,,,,
Stellar astronomy,Stellar types,Emission line stars,Symbiotic binary stars,Z Andromedae stars,,,,,

**Gamma ray observatories might be on the ground**
Observational astronomy,Instrumentation,Observatories,Gamma-ray observatories,,,,,,
Observational astronomy,Instrumentation,Observatories,Space observatories,Gamma-ray observatories,,,,,

Stellar astronomy,Stellar remnants,Compact objects,Compact binary systems,Cataclysmic variable stars,SX Arietis variables,,,,
Stellar astronomy,Stellar remnants,Compact objects,Compact binary systems,Cataclysmic variable stars,Novae,Dwarf novae,SX Arietis variables,,

Galactic and extragalactic astronomy,Galaxies,Active galaxies,Blazars,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Active galactic nuclei,Blazars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Am stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Magnetic stars,Magnetic variable stars,Am stars,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Strontium stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Heavy metal stars,Strontium stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Technetium stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Heavy metal stars,Technetium stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Manganese stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Ap stars,Manganese stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Manganese stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Heavy metal stars,Manganese stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Bp stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Magnetic stars,Bp stars,,,,,

Stellar astronomy,Stellar types,Chemically peculiar stars,Mercury-manganese stars,,,,,,
Stellar astronomy,Stellar types,Chemically peculiar stars,Magnetic stars,Mercury-manganese stars,,,,,

**Comment by BartlettAstro** [comment]
I am splitting this issue into individual issues so that we can deal with each pair as circumstances warrant. 

Issue #368 
Galactic and extragalactic astronomy,Galaxy physics,Galaxy dynamics,,,,,,,
Galactic and extragalactic astronomy,Galaxy physics,Galaxy processes,Galaxy dynamics,,,,,,

Issue #369
Galactic and extragalactic astronomy,Galaxies,Quasar-galaxy pairs,,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Active galactic nuclei,Quasars,Quasar-galaxy pairs,,,,

Issue #370
Galactic and extragalactic astronomy,Galaxies,Radio jets,,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Active galactic nuclei,Radio jets,,,,,

Issute #371
Galactic and extragalactic astronomy,Galaxies,Starburst galaxies,,,,,,,
Galactic and extragalactic astronomy,Galaxies,Active galaxies,Starburst galaxies,,,,,,

Issue #372
Solar system astronomy,Solar system,Oort cloud,,,,,,,
Solar system astronomy,Solar system,Small solar system bodies,Comets,Long period comets,Oort cloud,,,,

Issue #373
Solar system astronomy,Solar system,The Moon,,,,,,,
Solar system astronomy,Solar system,Natural satellites,The Moon,,,,,,

Issue #374
Solar system astronomy,Planetary science,Planetary atmospheres,Atmospheric tides,,,,,,
Solar system astronomy,Planetary science,Planetary atmospheres,Earth atmosphere,Atmospheric tides,,,,,

Issue #375
Solar system astronomy,Planetary science,Planetary atmospheres,Stratopause,,,,,,
Solar system astronomy,Planetary science,Planetary atmospheres,Earth atmosphere,Stratopause,,,,,

Issue #376
Solar system astronomy,Planetary science,Planetary atmospheres,Water vapor,,,,,,
Solar system astronomy,Planetary science,Planetary atmospheres,Earth atmosphere,Greenhouse gases,Water vapor,,,,

Issue  #377
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Beta Cephei stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Multi-periodic variable stars,Beta Cephei stars,,,

Issue #378
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Double-mode variable stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Multi-periodic variable stars,Double-mode variable stars,,,

Issue #379
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Delta Scuti variable stars,,,,
Stellar astronomy,Stellar types,Variable stars,Intrinsic variable stars,Pulsating variable stars,Multi-periodic variable stars,Delta Scuti variable stars,,,

**Comment by BartlettAstro** [comment]
All individual pairs listed here have either been resolved during release 5.0.0 (or earlier) or have transfered to their own issue for any further discussion.
