### ISSUE TITLE
Add concept: Kepler target stars, submitted by Megan Potterbusch (CfA) 10/9/2014

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#6]
Stars targeted by Kepler

Supporting Links:
http://iopscience.iop.org/2041-8205/713/2/L109/article
http://adsabs.harvard.edu/abs/2012ApJS..201...15H
http://adsabs.harvard.edu/abs/2012ApJ...753...90M
http://adsabs.harvard.edu/abs/2010ApJ...725.1226S
http://adsabs.harvard.edu/abs/2012ASPC..462..378K

**Comment by katieefrey** [comment]
@seweissman Sarah, could you (or Jenny, I just cant tag her here) think about this concept and give me some feedback?  I've dawdled on it for a while because I was wondering if I would see a real need for it, or concepts like it for other large observatories (i.e. HST and Webb) but my inclination is that this really shouldn't be a concept.

**Comment by seweissman** [comment]
@scfleming @dr-rodriguez Do you have any thoughts on this? 

We have Exoplanet Astronomy->Planet hosting stars. I am not sure we have concepts in the thesaurus at all right now related to observational targets in an abstract sense. I could see maybe adding a category like:

Exoplanet Astronomy->Exoplanet systems->[Exoplanet?] Candidate systems
and then having
Candidate Systems -> Target Stars
Candidate Systems -> Candidate Planets

I feel like I'd definitely like someone with exoplanet expertise to weigh in on this. I can try to get some more opinions.

**Comment by katieefrey** [comment]
I like the idea of general observational targets better than linking it to a specific telescope.  If you know people who would give some opinions, please do!

**Comment by scfleming** [comment]
It is definitely useful to know if a star was targeted by a misson, but I see UAT as more science categories and less about the observability history by a specific telescope.  I think @seweissman suggestion above makse some sense, although I worry about scope too, what is the level of requirement for something to be considered "targeted" as a planet search system?  Is it limited to a certain type of search, a certain set of telescopes?  What about exoplanet host stars that were found "by accident" even though they weren't specifically targeted by a mission's formal target list.

For my two cents, I'd *much* rather have a star be tagged as something like "Host To Confirmed Planet", "Host To Planet Candidate" and/or "Host To False Postive Planet", than whether it was targeted or not, at least in the context of UAT.  So my inclination is to not have this as a concept, but to perhaps review what's there for "hosts" in the context of exoplanets and their stellar systems.

Might also want to ping Susan Mullally at MAST for opinions on this!

**Comment by dr-rodriguez** [comment]
Pinging @mustaric
Susan has mentioned how varied the definitions of 'candidate' can be in the community alone, but I'm not sure how broadly the UAT has to address this. Maybe just having confirmed/candidate/false positive as Scott mentions above is enough.

I'm not sure about the idea of 'targeted' since you could consider nearly every star in the TIC to have been 'targeted' by TESS. Even after doing some magnitude cuts, you'd likely have millions of stars flagged as targets and at that point such a label can become meaningless.

**Comment by katieefrey** [comment]
> For my two cents, I'd _much_ rather have a star be tagged as something like "Host To Confirmed Planet", "Host To Planet Candidate" and/or "Host To False Postive Planet", than whether it was targeted or not, at least in the context of UAT. So my inclination is to not have this as a concept, but to perhaps review what's there for "hosts" in the context of exoplanets and their stellar systems.

The UAT does have a concept for "Planet hosting stars," but nothing for false positives or potential planets at the moment.

> I'm not sure about the idea of 'targeted' since you could consider nearly every star in the TIC to have been 'targeted' by TESS. Even after doing some magnitude cuts, you'd likely have millions of stars flagged as targets and at that point such a label can become meaningless.

Ah, yes, thanks, even a general target stars concept wont have much meaning as so many stars have been targeted.

**Comment by katieefrey** [comment]
Sounds like the general consensus is that this doesn't fit in the UAT, so I am closing the issue.  If anyone has further comments, they are welcome to re-open and add to the discussion.
