### ISSUE TITLE
Add wavelength ranges to the various types of astronomy under "methods", submitted by François Ochsenbein (CDS) 1/20/2017

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#76]
Include a definition or scope note for the different types of astronomy (infrared, radio, ultraviolet, etc) under Observational astronomy > Methods.

**Comment by BaptisteCecconi** [comment]
I'd say that the "Radio wave" range is too generic. We could think of ranges based on wavelengths: millimetric, centimetric, decimetric, metric, decametric, hectometric, kilometric, myriametric (for longer wavelengths). It might be too much, but science communities knows very well which radio wavelength range they do their science in.

**Comment by BartlettAstro** [comment]
The ranges proposed by @katieefrey seem reasonable, but I would like to look for a more authoritative source.  

As @BaptisteCecconi states, radio astronomers further subdivide their band passes. However, this concept is a general one and other concepts refer to narrower wavelength ranges; each of those should also have its appropriate range added to its definition as we audit concepts.

**Comment by BartlettAstro** [comment]
@ebortey Could you please create a separate issue for each segment of the electromagnetic spectrum that is associated with a direct child of Observational Astronomy (e.g. Gamma-ray astronomy, Infrared astronomy) and assess their definitions. Each of these concepts should have a definition from an authoritative source (usually [An Etymological Dictionary of Astronomy and Astrophysics](https://dictionary.obspm.fr/)) and an explicit statement of the associated wavelength range from an authoritative source.  You may need to be creative and combine multiple definitions.  To maintain the connection between this initiating issue and the issues for individual concepts, please mention this issue in each new issue you create as well as adding a mention of the new issues in a comment on this issue.

**Comment by BartlettAstro** [comment]
Issue #414 proposes new wording for the definition of Infrared astronomy.

**Comment by ebortey** [comment]
Issue #415 suggests a new definition of radar astronomy.
Issue #416 suggests a new definition of radio astronomy.
Issue #417 suggests a new definition of ultraviolet astronomy.
Issue #418 suggests a new definition of optical astronomy.
Issue #419 suggests a new definition of x-ray astronomy.
Issue #420 suggests a new definition of gamma-ray astronomy.

**Comment by BartlettAstro** [comment]
as listed above separate issues now add wavelength ranges to the definitions for each of the commonly named segments of the electromagnetic spectrum.
