### ISSUE TITLE
DQ Herculis stars subset of DQ stars?

### ISSUE THREAD

**Issue by katieefrey** [astrothesaurus/UAT#77]
Are "DQ Herculis stars" a subset of "DQ stars"?

**Comment by rpoleski** [comment]
No. Other name for "DQ Herculis stars" is "intermediate polars" (the latter is also more common in my opinion), while "DQ stars" is the name used for a subgroup of white dwarfs.

**Comment by katieefrey** [comment]
Hi @rpoleski , thanks for your comments!  I must have missed the notification, so my apologies for the delayed response.

A quick search of ADS supports your assessment that "intermediate polars" is more common, so I'll update this concept and set DQ Herc stars as a non-preferred version.
