### ISSUE TITLE
New thesaurus term suggestion:  star formation efficiency

### ISSUE THREAD

**Issue by uat-user** [astrothesaurus/UAT#83]
Review ID: 20170302162838_5209
 Comments: This version has a tonne of what look to me like synonyms showing. It's distracting and so I am finding myself picking the best synonym instead of the relevant/irrelevant terms. Example: Molecular versus giant molecular clouds. 
 DOI: http://dx.doi.org/10.3847/0004-6256/151/1/5

**Comment by katieefrey** [comment]
closing without action since there has been no further comment on this suggestion.  can be re-opened in the future
